package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class DsdTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsd_table.dsd_id
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    private Integer dsdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsd_table.name
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsd_table.age
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsd_table.dsd_id
     *
     * @return the value of dsd_table.dsd_id
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public Integer getDsdId() {
        return dsdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsd_table.dsd_id
     *
     * @param dsdId the value for dsd_table.dsd_id
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public void setDsdId(Integer dsdId) {
        this.dsdId = dsdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsd_table.name
     *
     * @return the value of dsd_table.name
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsd_table.name
     *
     * @param name the value for dsd_table.name
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsd_table.age
     *
     * @return the value of dsd_table.age
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsd_table.age
     *
     * @param age the value for dsd_table.age
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}