package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RiskEventsTrack implements Serializable {

    @Override
    public String toString() {
        return "RiskEventsTrack{" +
                "zId='" + zId + '\'' +
                ", zPersonnelId='" + zPersonnelId + '\'' +
                ", zCreatetime=" + zCreatetime +
                ", secretLevelId='" + secretLevelId + '\'' +
                ", nameTwo='" + nameTwo + '\'' +
                ", nameThree='" + nameThree + '\'' +
                ", eventsType='" + eventsType + '\'' +
                ", lawsuitProcedure='" + lawsuitProcedure + '\'' +
                ", beginMoney=" + beginMoney +
                ", endMoney=" + endMoney +
                ", eventsEnd='" + eventsEnd + '\'' +
                ", leader='" + leader + '\'' +
                ", relevantDepartment='" + relevantDepartment + '\'' +
                ", relevantPerson='" + relevantPerson + '\'' +
                ", tel='" + tel + '\'' +
                ", comment='" + comment + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.z_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String zId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.z_personnel_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String zPersonnelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.z_createtime_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private Date zCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.secret_level_id
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String secretLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.name_two_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String nameTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.name_three_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String nameThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.events_type_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String eventsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.lawsuit_procedure_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String lawsuitProcedure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.begin_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private BigDecimal beginMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.end_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private BigDecimal endMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.events_end_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String eventsEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.leader_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.relevant_department_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String relevantDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.relevant_person_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    private String relevantPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.tel_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.comment_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.z_id_
     *
     * @return the value of y_risk_events_track.z_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getzId() {
        return zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.z_id_
     *
     * @param zId the value for y_risk_events_track.z_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setzId(String zId) {
        this.zId = zId == null ? null : zId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.z_personnel_id_
     *
     * @return the value of y_risk_events_track.z_personnel_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getzPersonnelId() {
        return zPersonnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.z_personnel_id_
     *
     * @param zPersonnelId the value for y_risk_events_track.z_personnel_id_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setzPersonnelId(String zPersonnelId) {
        this.zPersonnelId = zPersonnelId == null ? null : zPersonnelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.z_createtime_
     *
     * @return the value of y_risk_events_track.z_createtime_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public Date getzCreatetime() {
        return zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.z_createtime_
     *
     * @param zCreatetime the value for y_risk_events_track.z_createtime_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setzCreatetime(Date zCreatetime) {
        this.zCreatetime = zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.secret_level_id
     *
     * @return the value of y_risk_events_track.secret_level_id
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getSecretLevelId() {
        return secretLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.secret_level_id
     *
     * @param secretLevelId the value for y_risk_events_track.secret_level_id
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setSecretLevelId(String secretLevelId) {
        this.secretLevelId = secretLevelId == null ? null : secretLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.name_two_
     *
     * @return the value of y_risk_events_track.name_two_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getNameTwo() {
        return nameTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.name_two_
     *
     * @param nameTwo the value for y_risk_events_track.name_two_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setNameTwo(String nameTwo) {
        this.nameTwo = nameTwo == null ? null : nameTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.name_three_
     *
     * @return the value of y_risk_events_track.name_three_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getNameThree() {
        return nameThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.name_three_
     *
     * @param nameThree the value for y_risk_events_track.name_three_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setNameThree(String nameThree) {
        this.nameThree = nameThree == null ? null : nameThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.events_type_
     *
     * @return the value of y_risk_events_track.events_type_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getEventsType() {
        return eventsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.events_type_
     *
     * @param eventsType the value for y_risk_events_track.events_type_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setEventsType(String eventsType) {
        this.eventsType = eventsType == null ? null : eventsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.lawsuit_procedure_
     *
     * @return the value of y_risk_events_track.lawsuit_procedure_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getLawsuitProcedure() {
        return lawsuitProcedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.lawsuit_procedure_
     *
     * @param lawsuitProcedure the value for y_risk_events_track.lawsuit_procedure_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setLawsuitProcedure(String lawsuitProcedure) {
        this.lawsuitProcedure = lawsuitProcedure == null ? null : lawsuitProcedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.begin_money_
     *
     * @return the value of y_risk_events_track.begin_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public BigDecimal getBeginMoney() {
        return beginMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.begin_money_
     *
     * @param beginMoney the value for y_risk_events_track.begin_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setBeginMoney(BigDecimal beginMoney) {
        this.beginMoney = beginMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.end_money_
     *
     * @return the value of y_risk_events_track.end_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public BigDecimal getEndMoney() {
        return endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.end_money_
     *
     * @param endMoney the value for y_risk_events_track.end_money_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setEndMoney(BigDecimal endMoney) {
        this.endMoney = endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.events_end_
     *
     * @return the value of y_risk_events_track.events_end_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getEventsEnd() {
        return eventsEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.events_end_
     *
     * @param eventsEnd the value for y_risk_events_track.events_end_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setEventsEnd(String eventsEnd) {
        this.eventsEnd = eventsEnd == null ? null : eventsEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.leader_
     *
     * @return the value of y_risk_events_track.leader_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.leader_
     *
     * @param leader the value for y_risk_events_track.leader_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.relevant_department_
     *
     * @return the value of y_risk_events_track.relevant_department_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getRelevantDepartment() {
        return relevantDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.relevant_department_
     *
     * @param relevantDepartment the value for y_risk_events_track.relevant_department_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setRelevantDepartment(String relevantDepartment) {
        this.relevantDepartment = relevantDepartment == null ? null : relevantDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.relevant_person_
     *
     * @return the value of y_risk_events_track.relevant_person_
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getRelevantPerson() {
        return relevantPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.relevant_person_
     *
     * @param relevantPerson the value for y_risk_events_track.relevant_person_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setRelevantPerson(String relevantPerson) {
        this.relevantPerson = relevantPerson == null ? null : relevantPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.tel_
     *
     * @return the value of y_risk_events_track.tel_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.tel_
     *
     * @param tel the value for y_risk_events_track.tel_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.comment_
     *
     * @return the value of y_risk_events_track.comment_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.comment_
     *
     * @param comment the value for y_risk_events_track.comment_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}