package com.casic.oarp.datavisual.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RiskEventsTrackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public RiskEventsTrackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZIdIsNull() {
            addCriterion("z_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZIdIsNotNull() {
            addCriterion("z_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZIdEqualTo(String value) {
            addCriterion("z_id_ =", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotEqualTo(String value) {
            addCriterion("z_id_ <>", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThan(String value) {
            addCriterion("z_id_ >", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_id_ >=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThan(String value) {
            addCriterion("z_id_ <", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThanOrEqualTo(String value) {
            addCriterion("z_id_ <=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLike(String value) {
            addCriterion("z_id_ like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotLike(String value) {
            addCriterion("z_id_ not like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdIn(List<String> values) {
            addCriterion("z_id_ in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotIn(List<String> values) {
            addCriterion("z_id_ not in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdBetween(String value1, String value2) {
            addCriterion("z_id_ between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotBetween(String value1, String value2) {
            addCriterion("z_id_ not between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNull() {
            addCriterion("z_personnel_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNotNull() {
            addCriterion("z_personnel_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdEqualTo(String value) {
            addCriterion("z_personnel_id_ =", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotEqualTo(String value) {
            addCriterion("z_personnel_id_ <>", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThan(String value) {
            addCriterion("z_personnel_id_ >", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ >=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThan(String value) {
            addCriterion("z_personnel_id_ <", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ <=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLike(String value) {
            addCriterion("z_personnel_id_ like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotLike(String value) {
            addCriterion("z_personnel_id_ not like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIn(List<String> values) {
            addCriterion("z_personnel_id_ in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotIn(List<String> values) {
            addCriterion("z_personnel_id_ not in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ not between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNull() {
            addCriterion("z_createtime_ is null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNotNull() {
            addCriterion("z_createtime_ is not null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeEqualTo(Date value) {
            addCriterion("z_createtime_ =", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotEqualTo(Date value) {
            addCriterion("z_createtime_ <>", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThan(Date value) {
            addCriterion("z_createtime_ >", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ >=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThan(Date value) {
            addCriterion("z_createtime_ <", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ <=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIn(List<Date> values) {
            addCriterion("z_createtime_ in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotIn(List<Date> values) {
            addCriterion("z_createtime_ not in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ not between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNull() {
            addCriterion("secret_level_id is null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNotNull() {
            addCriterion("secret_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdEqualTo(String value) {
            addCriterion("secret_level_id =", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotEqualTo(String value) {
            addCriterion("secret_level_id <>", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThan(String value) {
            addCriterion("secret_level_id >", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThanOrEqualTo(String value) {
            addCriterion("secret_level_id >=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThan(String value) {
            addCriterion("secret_level_id <", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThanOrEqualTo(String value) {
            addCriterion("secret_level_id <=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLike(String value) {
            addCriterion("secret_level_id like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotLike(String value) {
            addCriterion("secret_level_id not like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIn(List<String> values) {
            addCriterion("secret_level_id in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotIn(List<String> values) {
            addCriterion("secret_level_id not in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdBetween(String value1, String value2) {
            addCriterion("secret_level_id between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotBetween(String value1, String value2) {
            addCriterion("secret_level_id not between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andNameTwoIsNull() {
            addCriterion("name_two_ is null");
            return (Criteria) this;
        }

        public Criteria andNameTwoIsNotNull() {
            addCriterion("name_two_ is not null");
            return (Criteria) this;
        }

        public Criteria andNameTwoEqualTo(String value) {
            addCriterion("name_two_ =", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoNotEqualTo(String value) {
            addCriterion("name_two_ <>", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoGreaterThan(String value) {
            addCriterion("name_two_ >", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoGreaterThanOrEqualTo(String value) {
            addCriterion("name_two_ >=", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoLessThan(String value) {
            addCriterion("name_two_ <", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoLessThanOrEqualTo(String value) {
            addCriterion("name_two_ <=", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoLike(String value) {
            addCriterion("name_two_ like", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoNotLike(String value) {
            addCriterion("name_two_ not like", value, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoIn(List<String> values) {
            addCriterion("name_two_ in", values, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoNotIn(List<String> values) {
            addCriterion("name_two_ not in", values, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoBetween(String value1, String value2) {
            addCriterion("name_two_ between", value1, value2, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameTwoNotBetween(String value1, String value2) {
            addCriterion("name_two_ not between", value1, value2, "nameTwo");
            return (Criteria) this;
        }

        public Criteria andNameThreeIsNull() {
            addCriterion("name_three_ is null");
            return (Criteria) this;
        }

        public Criteria andNameThreeIsNotNull() {
            addCriterion("name_three_ is not null");
            return (Criteria) this;
        }

        public Criteria andNameThreeEqualTo(String value) {
            addCriterion("name_three_ =", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeNotEqualTo(String value) {
            addCriterion("name_three_ <>", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeGreaterThan(String value) {
            addCriterion("name_three_ >", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeGreaterThanOrEqualTo(String value) {
            addCriterion("name_three_ >=", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeLessThan(String value) {
            addCriterion("name_three_ <", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeLessThanOrEqualTo(String value) {
            addCriterion("name_three_ <=", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeLike(String value) {
            addCriterion("name_three_ like", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeNotLike(String value) {
            addCriterion("name_three_ not like", value, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeIn(List<String> values) {
            addCriterion("name_three_ in", values, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeNotIn(List<String> values) {
            addCriterion("name_three_ not in", values, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeBetween(String value1, String value2) {
            addCriterion("name_three_ between", value1, value2, "nameThree");
            return (Criteria) this;
        }

        public Criteria andNameThreeNotBetween(String value1, String value2) {
            addCriterion("name_three_ not between", value1, value2, "nameThree");
            return (Criteria) this;
        }

        public Criteria andEventsTypeIsNull() {
            addCriterion("events_type_ is null");
            return (Criteria) this;
        }

        public Criteria andEventsTypeIsNotNull() {
            addCriterion("events_type_ is not null");
            return (Criteria) this;
        }

        public Criteria andEventsTypeEqualTo(String value) {
            addCriterion("events_type_ =", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeNotEqualTo(String value) {
            addCriterion("events_type_ <>", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeGreaterThan(String value) {
            addCriterion("events_type_ >", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("events_type_ >=", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeLessThan(String value) {
            addCriterion("events_type_ <", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeLessThanOrEqualTo(String value) {
            addCriterion("events_type_ <=", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeLike(String value) {
            addCriterion("events_type_ like", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeNotLike(String value) {
            addCriterion("events_type_ not like", value, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeIn(List<String> values) {
            addCriterion("events_type_ in", values, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeNotIn(List<String> values) {
            addCriterion("events_type_ not in", values, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeBetween(String value1, String value2) {
            addCriterion("events_type_ between", value1, value2, "eventsType");
            return (Criteria) this;
        }

        public Criteria andEventsTypeNotBetween(String value1, String value2) {
            addCriterion("events_type_ not between", value1, value2, "eventsType");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureIsNull() {
            addCriterion("lawsuit_procedure_ is null");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureIsNotNull() {
            addCriterion("lawsuit_procedure_ is not null");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureEqualTo(String value) {
            addCriterion("lawsuit_procedure_ =", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureNotEqualTo(String value) {
            addCriterion("lawsuit_procedure_ <>", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureGreaterThan(String value) {
            addCriterion("lawsuit_procedure_ >", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureGreaterThanOrEqualTo(String value) {
            addCriterion("lawsuit_procedure_ >=", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureLessThan(String value) {
            addCriterion("lawsuit_procedure_ <", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureLessThanOrEqualTo(String value) {
            addCriterion("lawsuit_procedure_ <=", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureLike(String value) {
            addCriterion("lawsuit_procedure_ like", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureNotLike(String value) {
            addCriterion("lawsuit_procedure_ not like", value, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureIn(List<String> values) {
            addCriterion("lawsuit_procedure_ in", values, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureNotIn(List<String> values) {
            addCriterion("lawsuit_procedure_ not in", values, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureBetween(String value1, String value2) {
            addCriterion("lawsuit_procedure_ between", value1, value2, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andLawsuitProcedureNotBetween(String value1, String value2) {
            addCriterion("lawsuit_procedure_ not between", value1, value2, "lawsuitProcedure");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyIsNull() {
            addCriterion("begin_money_ is null");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyIsNotNull() {
            addCriterion("begin_money_ is not null");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyEqualTo(BigDecimal value) {
            addCriterion("begin_money_ =", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyNotEqualTo(BigDecimal value) {
            addCriterion("begin_money_ <>", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyGreaterThan(BigDecimal value) {
            addCriterion("begin_money_ >", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("begin_money_ >=", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyLessThan(BigDecimal value) {
            addCriterion("begin_money_ <", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("begin_money_ <=", value, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyIn(List<BigDecimal> values) {
            addCriterion("begin_money_ in", values, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyNotIn(List<BigDecimal> values) {
            addCriterion("begin_money_ not in", values, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("begin_money_ between", value1, value2, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andBeginMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("begin_money_ not between", value1, value2, "beginMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyIsNull() {
            addCriterion("end_money_ is null");
            return (Criteria) this;
        }

        public Criteria andEndMoneyIsNotNull() {
            addCriterion("end_money_ is not null");
            return (Criteria) this;
        }

        public Criteria andEndMoneyEqualTo(BigDecimal value) {
            addCriterion("end_money_ =", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyNotEqualTo(BigDecimal value) {
            addCriterion("end_money_ <>", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyGreaterThan(BigDecimal value) {
            addCriterion("end_money_ >", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("end_money_ >=", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyLessThan(BigDecimal value) {
            addCriterion("end_money_ <", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("end_money_ <=", value, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyIn(List<BigDecimal> values) {
            addCriterion("end_money_ in", values, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyNotIn(List<BigDecimal> values) {
            addCriterion("end_money_ not in", values, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("end_money_ between", value1, value2, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEndMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("end_money_ not between", value1, value2, "endMoney");
            return (Criteria) this;
        }

        public Criteria andEventsEndIsNull() {
            addCriterion("events_end_ is null");
            return (Criteria) this;
        }

        public Criteria andEventsEndIsNotNull() {
            addCriterion("events_end_ is not null");
            return (Criteria) this;
        }

        public Criteria andEventsEndEqualTo(String value) {
            addCriterion("events_end_ =", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndNotEqualTo(String value) {
            addCriterion("events_end_ <>", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndGreaterThan(String value) {
            addCriterion("events_end_ >", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndGreaterThanOrEqualTo(String value) {
            addCriterion("events_end_ >=", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndLessThan(String value) {
            addCriterion("events_end_ <", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndLessThanOrEqualTo(String value) {
            addCriterion("events_end_ <=", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndLike(String value) {
            addCriterion("events_end_ like", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndNotLike(String value) {
            addCriterion("events_end_ not like", value, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndIn(List<String> values) {
            addCriterion("events_end_ in", values, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndNotIn(List<String> values) {
            addCriterion("events_end_ not in", values, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndBetween(String value1, String value2) {
            addCriterion("events_end_ between", value1, value2, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andEventsEndNotBetween(String value1, String value2) {
            addCriterion("events_end_ not between", value1, value2, "eventsEnd");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNull() {
            addCriterion("leader_ is null");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNotNull() {
            addCriterion("leader_ is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderEqualTo(String value) {
            addCriterion("leader_ =", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotEqualTo(String value) {
            addCriterion("leader_ <>", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThan(String value) {
            addCriterion("leader_ >", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("leader_ >=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThan(String value) {
            addCriterion("leader_ <", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThanOrEqualTo(String value) {
            addCriterion("leader_ <=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLike(String value) {
            addCriterion("leader_ like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotLike(String value) {
            addCriterion("leader_ not like", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderIn(List<String> values) {
            addCriterion("leader_ in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotIn(List<String> values) {
            addCriterion("leader_ not in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderBetween(String value1, String value2) {
            addCriterion("leader_ between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotBetween(String value1, String value2) {
            addCriterion("leader_ not between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentIsNull() {
            addCriterion("relevant_department_ is null");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentIsNotNull() {
            addCriterion("relevant_department_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentEqualTo(String value) {
            addCriterion("relevant_department_ =", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentNotEqualTo(String value) {
            addCriterion("relevant_department_ <>", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentGreaterThan(String value) {
            addCriterion("relevant_department_ >", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("relevant_department_ >=", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentLessThan(String value) {
            addCriterion("relevant_department_ <", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentLessThanOrEqualTo(String value) {
            addCriterion("relevant_department_ <=", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentLike(String value) {
            addCriterion("relevant_department_ like", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentNotLike(String value) {
            addCriterion("relevant_department_ not like", value, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentIn(List<String> values) {
            addCriterion("relevant_department_ in", values, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentNotIn(List<String> values) {
            addCriterion("relevant_department_ not in", values, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentBetween(String value1, String value2) {
            addCriterion("relevant_department_ between", value1, value2, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantDepartmentNotBetween(String value1, String value2) {
            addCriterion("relevant_department_ not between", value1, value2, "relevantDepartment");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonIsNull() {
            addCriterion("relevant_person_ is null");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonIsNotNull() {
            addCriterion("relevant_person_ is not null");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonEqualTo(String value) {
            addCriterion("relevant_person_ =", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonNotEqualTo(String value) {
            addCriterion("relevant_person_ <>", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonGreaterThan(String value) {
            addCriterion("relevant_person_ >", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonGreaterThanOrEqualTo(String value) {
            addCriterion("relevant_person_ >=", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonLessThan(String value) {
            addCriterion("relevant_person_ <", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonLessThanOrEqualTo(String value) {
            addCriterion("relevant_person_ <=", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonLike(String value) {
            addCriterion("relevant_person_ like", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonNotLike(String value) {
            addCriterion("relevant_person_ not like", value, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonIn(List<String> values) {
            addCriterion("relevant_person_ in", values, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonNotIn(List<String> values) {
            addCriterion("relevant_person_ not in", values, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonBetween(String value1, String value2) {
            addCriterion("relevant_person_ between", value1, value2, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andRelevantPersonNotBetween(String value1, String value2) {
            addCriterion("relevant_person_ not between", value1, value2, "relevantPerson");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel_ is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel_ is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel_ =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel_ <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel_ >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel_ >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel_ <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel_ <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel_ like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel_ not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel_ in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel_ not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel_ between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel_ not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment_ is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment_ is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment_ =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment_ <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment_ >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment_ >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment_ <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment_ <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment_ like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment_ not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment_ in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment_ not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment_ between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment_ not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_risk_events_track
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 04 10:51:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}