package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class RiskEventsTrackWithBLOBs extends RiskEventsTrack implements Serializable {

    @Override
    public String toString() {
        return "RiskEventsTrackWithBLOBs{" +
                "eventsDescribe='" + eventsDescribe + '\'' +
                ", causeAnalyze='" + causeAnalyze + '\'' +
                ", riskEventsProgress='" + riskEventsProgress + '\'' +
                ", solutions='" + solutions + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.events_describe_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String eventsDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.cause_analyze_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String causeAnalyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.risk_events_progress_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String riskEventsProgress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_risk_events_track.solutions_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private String solutions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.events_describe_
     *
     * @return the value of y_risk_events_track.events_describe_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getEventsDescribe() {
        return eventsDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.events_describe_
     *
     * @param eventsDescribe the value for y_risk_events_track.events_describe_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setEventsDescribe(String eventsDescribe) {
        this.eventsDescribe = eventsDescribe == null ? null : eventsDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.cause_analyze_
     *
     * @return the value of y_risk_events_track.cause_analyze_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getCauseAnalyze() {
        return causeAnalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.cause_analyze_
     *
     * @param causeAnalyze the value for y_risk_events_track.cause_analyze_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setCauseAnalyze(String causeAnalyze) {
        this.causeAnalyze = causeAnalyze == null ? null : causeAnalyze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.risk_events_progress_
     *
     * @return the value of y_risk_events_track.risk_events_progress_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getRiskEventsProgress() {
        return riskEventsProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.risk_events_progress_
     *
     * @param riskEventsProgress the value for y_risk_events_track.risk_events_progress_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setRiskEventsProgress(String riskEventsProgress) {
        this.riskEventsProgress = riskEventsProgress == null ? null : riskEventsProgress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_risk_events_track.solutions_
     *
     * @return the value of y_risk_events_track.solutions_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public String getSolutions() {
        return solutions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_risk_events_track.solutions_
     *
     * @param solutions the value for y_risk_events_track.solutions_
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    public void setSolutions(String solutions) {
        this.solutions = solutions == null ? null : solutions.trim();
    }
}