package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class ShenjfxwtbajzggzqkbWithBLOBs extends Shenjfxwtbajzggzqkb implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjyj
     *  审计意见
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.lingdps
     * 领导批示
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String lingdps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjxmmc
     * 审计项目名称
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjxmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentms
     * 问题描述
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.yuanyfx
     * 原因分析
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String yuanyfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zerjz
     * 责任追究
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zerjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shixzg
     * 事项整改
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shixzg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.juyfszg
     * 举一反三整改
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String juyfszg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.yuantzgjz
     * 源头整改进展情况
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String yuantzgjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.beiz
     * 备注
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String beiz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_shenjfxwtbajzggzqkb
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shenjyj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shenjyj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShenjyj() {
        return shenjyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shenjyj
     *
     * @param shenjyj the value for y_shenjfxwtbajzggzqkb.shenjyj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShenjyj(String shenjyj) {
        this.shenjyj = shenjyj == null ? null : shenjyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.lingdps
     *
     * @return the value of y_shenjfxwtbajzggzqkb.lingdps
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getLingdps() {
        return lingdps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.lingdps
     *
     * @param lingdps the value for y_shenjfxwtbajzggzqkb.lingdps
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setLingdps(String lingdps) {
        this.lingdps = lingdps == null ? null : lingdps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shenjxmmc
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shenjxmmc
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShenjxmmc() {
        return shenjxmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shenjxmmc
     *
     * @param shenjxmmc the value for y_shenjfxwtbajzggzqkb.shenjxmmc
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShenjxmmc(String shenjxmmc) {
        this.shenjxmmc = shenjxmmc == null ? null : shenjxmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentms
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentms
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentms() {
        return wentms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentms
     *
     * @param wentms the value for y_shenjfxwtbajzggzqkb.wentms
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentms(String wentms) {
        this.wentms = wentms == null ? null : wentms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.yuanyfx
     *
     * @return the value of y_shenjfxwtbajzggzqkb.yuanyfx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getYuanyfx() {
        return yuanyfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.yuanyfx
     *
     * @param yuanyfx the value for y_shenjfxwtbajzggzqkb.yuanyfx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setYuanyfx(String yuanyfx) {
        this.yuanyfx = yuanyfx == null ? null : yuanyfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zerjz
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zerjz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZerjz() {
        return zerjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zerjz
     *
     * @param zerjz the value for y_shenjfxwtbajzggzqkb.zerjz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZerjz(String zerjz) {
        this.zerjz = zerjz == null ? null : zerjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shixzg
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shixzg
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShixzg() {
        return shixzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shixzg
     *
     * @param shixzg the value for y_shenjfxwtbajzggzqkb.shixzg
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShixzg(String shixzg) {
        this.shixzg = shixzg == null ? null : shixzg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.juyfszg
     *
     * @return the value of y_shenjfxwtbajzggzqkb.juyfszg
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getJuyfszg() {
        return juyfszg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.juyfszg
     *
     * @param juyfszg the value for y_shenjfxwtbajzggzqkb.juyfszg
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setJuyfszg(String juyfszg) {
        this.juyfszg = juyfszg == null ? null : juyfszg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.yuantzgjz
     *
     * @return the value of y_shenjfxwtbajzggzqkb.yuantzgjz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getYuantzgjz() {
        return yuantzgjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.yuantzgjz
     *
     * @param yuantzgjz the value for y_shenjfxwtbajzggzqkb.yuantzgjz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setYuantzgjz(String yuantzgjz) {
        this.yuantzgjz = yuantzgjz == null ? null : yuantzgjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.beiz
     *
     * @return the value of y_shenjfxwtbajzggzqkb.beiz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getBeiz() {
        return beiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.beiz
     *
     * @param beiz the value for y_shenjfxwtbajzggzqkb.beiz
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setBeiz(String beiz) {
        this.beiz = beiz == null ? null : beiz.trim();
    }
}