package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Shenjfxwtbajzggzqkb implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.z_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.susejdw
     * 所属二级单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String susejdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjxmlx
     * 审计项目类型
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjxmlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.beisjdw
     * 被审计单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String beisjdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.danwjc
     * 单位级次
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String danwjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjdw
     * 审计单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.neiwbsj
     * 内外部审计
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String neiwbsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.xiadyjsj
     * 下达意见时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date xiadyjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentlx
     * 问题类型
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentje
     * 问题金额
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private BigDecimal wentje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhongycd
     * 重要程度
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhongycd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhenggzrr
     * 整改责任人
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhenggzrr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhenggzrbm
     * 整改责任部门
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhenggzrbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.jihwcsj
     * 计划完成时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date jihwcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shijwcsj
     * 实际完成时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date shijwcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhenggzt
     * 整改状态
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhenggzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.z_personnel_id_
     * 创建人
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zPersonnelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.secret_level_id
     * 密级
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String secretLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.z_createtime_
     * 创建时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date zCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentfssj
     * 问题发生时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date wentfssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.z_project_id_
     * 项目ID
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.duczgbm
     * 督促整改部门
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String duczgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.jiansdw
     * 建设单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String jiansdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wancxs
     * 完成形式
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wancxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shijap
     * 时间安排
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shijap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.dangzjcfqk
     * 党政纪处分情况
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String dangzjcfqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhuzclqk
     * 组织处理情况
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhuzclqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.qitwzqk
     * 其他问责情况
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String qitwzqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.houxqhcs
     * 后续强化措施
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String houxqhcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.last_update_time
     * 最后更新时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhenggjd
     * 整改进度
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhenggjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.beisjdwid
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String beisjdwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentsx1
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentsx1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentsx2
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentsx2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentsx3
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentsx3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentsx4
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentsx4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.year_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.year_month_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String yearMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.create_corporation_name
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String createCorporationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.create_corporation_id
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String createCorporationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_shenjfxwtbajzggzqkb
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.z_id_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.z_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getzId() {
        return zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.z_id_
     *
     * @param zId the value for y_shenjfxwtbajzggzqkb.z_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setzId(String zId) {
        this.zId = zId == null ? null : zId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.susejdw
     *
     * @return the value of y_shenjfxwtbajzggzqkb.susejdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getSusejdw() {
        return susejdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.susejdw
     *
     * @param susejdw the value for y_shenjfxwtbajzggzqkb.susejdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setSusejdw(String susejdw) {
        this.susejdw = susejdw == null ? null : susejdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shenjxmlx
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shenjxmlx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShenjxmlx() {
        return shenjxmlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shenjxmlx
     *
     * @param shenjxmlx the value for y_shenjfxwtbajzggzqkb.shenjxmlx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShenjxmlx(String shenjxmlx) {
        this.shenjxmlx = shenjxmlx == null ? null : shenjxmlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.beisjdw
     *
     * @return the value of y_shenjfxwtbajzggzqkb.beisjdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getBeisjdw() {
        return beisjdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.beisjdw
     *
     * @param beisjdw the value for y_shenjfxwtbajzggzqkb.beisjdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setBeisjdw(String beisjdw) {
        this.beisjdw = beisjdw == null ? null : beisjdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.danwjc
     *
     * @return the value of y_shenjfxwtbajzggzqkb.danwjc
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getDanwjc() {
        return danwjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.danwjc
     *
     * @param danwjc the value for y_shenjfxwtbajzggzqkb.danwjc
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setDanwjc(String danwjc) {
        this.danwjc = danwjc == null ? null : danwjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shenjdw
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shenjdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShenjdw() {
        return shenjdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shenjdw
     *
     * @param shenjdw the value for y_shenjfxwtbajzggzqkb.shenjdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShenjdw(String shenjdw) {
        this.shenjdw = shenjdw == null ? null : shenjdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.neiwbsj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.neiwbsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getNeiwbsj() {
        return neiwbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.neiwbsj
     *
     * @param neiwbsj the value for y_shenjfxwtbajzggzqkb.neiwbsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setNeiwbsj(String neiwbsj) {
        this.neiwbsj = neiwbsj == null ? null : neiwbsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.xiadyjsj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.xiadyjsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getXiadyjsj() {
        return xiadyjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.xiadyjsj
     *
     * @param xiadyjsj the value for y_shenjfxwtbajzggzqkb.xiadyjsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setXiadyjsj(Date xiadyjsj) {
        this.xiadyjsj = xiadyjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentlx
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentlx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentlx() {
        return wentlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentlx
     *
     * @param wentlx the value for y_shenjfxwtbajzggzqkb.wentlx
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentlx(String wentlx) {
        this.wentlx = wentlx == null ? null : wentlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentje
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentje
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public BigDecimal getWentje() {
        return wentje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentje
     *
     * @param wentje the value for y_shenjfxwtbajzggzqkb.wentje
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentje(BigDecimal wentje) {
        this.wentje = wentje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhongycd
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhongycd
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhongycd() {
        return zhongycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhongycd
     *
     * @param zhongycd the value for y_shenjfxwtbajzggzqkb.zhongycd
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhongycd(String zhongycd) {
        this.zhongycd = zhongycd == null ? null : zhongycd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhenggzrr
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhenggzrr
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhenggzrr() {
        return zhenggzrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhenggzrr
     *
     * @param zhenggzrr the value for y_shenjfxwtbajzggzqkb.zhenggzrr
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhenggzrr(String zhenggzrr) {
        this.zhenggzrr = zhenggzrr == null ? null : zhenggzrr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhenggzrbm
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhenggzrbm
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhenggzrbm() {
        return zhenggzrbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhenggzrbm
     *
     * @param zhenggzrbm the value for y_shenjfxwtbajzggzqkb.zhenggzrbm
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhenggzrbm(String zhenggzrbm) {
        this.zhenggzrbm = zhenggzrbm == null ? null : zhenggzrbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.jihwcsj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.jihwcsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getJihwcsj() {
        return jihwcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.jihwcsj
     *
     * @param jihwcsj the value for y_shenjfxwtbajzggzqkb.jihwcsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setJihwcsj(Date jihwcsj) {
        this.jihwcsj = jihwcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shijwcsj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shijwcsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getShijwcsj() {
        return shijwcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shijwcsj
     *
     * @param shijwcsj the value for y_shenjfxwtbajzggzqkb.shijwcsj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShijwcsj(Date shijwcsj) {
        this.shijwcsj = shijwcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhenggzt
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhenggzt
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhenggzt() {
        return zhenggzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhenggzt
     *
     * @param zhenggzt the value for y_shenjfxwtbajzggzqkb.zhenggzt
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhenggzt(String zhenggzt) {
        this.zhenggzt = zhenggzt == null ? null : zhenggzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.z_personnel_id_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.z_personnel_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getzPersonnelId() {
        return zPersonnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.z_personnel_id_
     *
     * @param zPersonnelId the value for y_shenjfxwtbajzggzqkb.z_personnel_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setzPersonnelId(String zPersonnelId) {
        this.zPersonnelId = zPersonnelId == null ? null : zPersonnelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.secret_level_id
     *
     * @return the value of y_shenjfxwtbajzggzqkb.secret_level_id
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getSecretLevelId() {
        return secretLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.secret_level_id
     *
     * @param secretLevelId the value for y_shenjfxwtbajzggzqkb.secret_level_id
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setSecretLevelId(String secretLevelId) {
        this.secretLevelId = secretLevelId == null ? null : secretLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.z_createtime_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.z_createtime_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getzCreatetime() {
        return zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.z_createtime_
     *
     * @param zCreatetime the value for y_shenjfxwtbajzggzqkb.z_createtime_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setzCreatetime(Date zCreatetime) {
        this.zCreatetime = zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentfssj
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentfssj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getWentfssj() {
        return wentfssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentfssj
     *
     * @param wentfssj the value for y_shenjfxwtbajzggzqkb.wentfssj
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentfssj(Date wentfssj) {
        this.wentfssj = wentfssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.z_project_id_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.z_project_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getzProjectId() {
        return zProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.z_project_id_
     *
     * @param zProjectId the value for y_shenjfxwtbajzggzqkb.z_project_id_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setzProjectId(String zProjectId) {
        this.zProjectId = zProjectId == null ? null : zProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.duczgbm
     *
     * @return the value of y_shenjfxwtbajzggzqkb.duczgbm
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getDuczgbm() {
        return duczgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.duczgbm
     *
     * @param duczgbm the value for y_shenjfxwtbajzggzqkb.duczgbm
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setDuczgbm(String duczgbm) {
        this.duczgbm = duczgbm == null ? null : duczgbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.jiansdw
     *
     * @return the value of y_shenjfxwtbajzggzqkb.jiansdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getJiansdw() {
        return jiansdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.jiansdw
     *
     * @param jiansdw the value for y_shenjfxwtbajzggzqkb.jiansdw
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setJiansdw(String jiansdw) {
        this.jiansdw = jiansdw == null ? null : jiansdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wancxs
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wancxs
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWancxs() {
        return wancxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wancxs
     *
     * @param wancxs the value for y_shenjfxwtbajzggzqkb.wancxs
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWancxs(String wancxs) {
        this.wancxs = wancxs == null ? null : wancxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.shijap
     *
     * @return the value of y_shenjfxwtbajzggzqkb.shijap
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getShijap() {
        return shijap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.shijap
     *
     * @param shijap the value for y_shenjfxwtbajzggzqkb.shijap
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setShijap(String shijap) {
        this.shijap = shijap == null ? null : shijap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.dangzjcfqk
     *
     * @return the value of y_shenjfxwtbajzggzqkb.dangzjcfqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getDangzjcfqk() {
        return dangzjcfqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.dangzjcfqk
     *
     * @param dangzjcfqk the value for y_shenjfxwtbajzggzqkb.dangzjcfqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setDangzjcfqk(String dangzjcfqk) {
        this.dangzjcfqk = dangzjcfqk == null ? null : dangzjcfqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhuzclqk
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhuzclqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhuzclqk() {
        return zhuzclqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhuzclqk
     *
     * @param zhuzclqk the value for y_shenjfxwtbajzggzqkb.zhuzclqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhuzclqk(String zhuzclqk) {
        this.zhuzclqk = zhuzclqk == null ? null : zhuzclqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.qitwzqk
     *
     * @return the value of y_shenjfxwtbajzggzqkb.qitwzqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getQitwzqk() {
        return qitwzqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.qitwzqk
     *
     * @param qitwzqk the value for y_shenjfxwtbajzggzqkb.qitwzqk
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setQitwzqk(String qitwzqk) {
        this.qitwzqk = qitwzqk == null ? null : qitwzqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.houxqhcs
     *
     * @return the value of y_shenjfxwtbajzggzqkb.houxqhcs
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getHouxqhcs() {
        return houxqhcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.houxqhcs
     *
     * @param houxqhcs the value for y_shenjfxwtbajzggzqkb.houxqhcs
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setHouxqhcs(String houxqhcs) {
        this.houxqhcs = houxqhcs == null ? null : houxqhcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.last_update_time
     *
     * @return the value of y_shenjfxwtbajzggzqkb.last_update_time
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.last_update_time
     *
     * @param lastUpdateTime the value for y_shenjfxwtbajzggzqkb.last_update_time
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.zhenggjd
     *
     * @return the value of y_shenjfxwtbajzggzqkb.zhenggjd
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getZhenggjd() {
        return zhenggjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.zhenggjd
     *
     * @param zhenggjd the value for y_shenjfxwtbajzggzqkb.zhenggjd
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setZhenggjd(String zhenggjd) {
        this.zhenggjd = zhenggjd == null ? null : zhenggjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.beisjdwid
     *
     * @return the value of y_shenjfxwtbajzggzqkb.beisjdwid
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getBeisjdwid() {
        return beisjdwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.beisjdwid
     *
     * @param beisjdwid the value for y_shenjfxwtbajzggzqkb.beisjdwid
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setBeisjdwid(String beisjdwid) {
        this.beisjdwid = beisjdwid == null ? null : beisjdwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentsx1
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentsx1
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentsx1() {
        return wentsx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentsx1
     *
     * @param wentsx1 the value for y_shenjfxwtbajzggzqkb.wentsx1
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentsx1(String wentsx1) {
        this.wentsx1 = wentsx1 == null ? null : wentsx1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentsx2
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentsx2
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentsx2() {
        return wentsx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentsx2
     *
     * @param wentsx2 the value for y_shenjfxwtbajzggzqkb.wentsx2
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentsx2(String wentsx2) {
        this.wentsx2 = wentsx2 == null ? null : wentsx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentsx3
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentsx3
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentsx3() {
        return wentsx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentsx3
     *
     * @param wentsx3 the value for y_shenjfxwtbajzggzqkb.wentsx3
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentsx3(String wentsx3) {
        this.wentsx3 = wentsx3 == null ? null : wentsx3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.wentsx4
     *
     * @return the value of y_shenjfxwtbajzggzqkb.wentsx4
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getWentsx4() {
        return wentsx4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.wentsx4
     *
     * @param wentsx4 the value for y_shenjfxwtbajzggzqkb.wentsx4
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setWentsx4(String wentsx4) {
        this.wentsx4 = wentsx4 == null ? null : wentsx4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.year_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.year_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.year_
     *
     * @param year the value for y_shenjfxwtbajzggzqkb.year_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.year_month_
     *
     * @return the value of y_shenjfxwtbajzggzqkb.year_month_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.year_month_
     *
     * @param yearMonth the value for y_shenjfxwtbajzggzqkb.year_month_
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setYearMonth(String yearMonth) {
        this.yearMonth = yearMonth == null ? null : yearMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.create_corporation_name
     *
     * @return the value of y_shenjfxwtbajzggzqkb.create_corporation_name
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getCreateCorporationName() {
        return createCorporationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.create_corporation_name
     *
     * @param createCorporationName the value for y_shenjfxwtbajzggzqkb.create_corporation_name
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setCreateCorporationName(String createCorporationName) {
        this.createCorporationName = createCorporationName == null ? null : createCorporationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_shenjfxwtbajzggzqkb.create_corporation_id
     *
     * @return the value of y_shenjfxwtbajzggzqkb.create_corporation_id
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public String getCreateCorporationId() {
        return createCorporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_shenjfxwtbajzggzqkb.create_corporation_id
     *
     * @param createCorporationId the value for y_shenjfxwtbajzggzqkb.create_corporation_id
     *
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    public void setCreateCorporationId(String createCorporationId) {
        this.createCorporationId = createCorporationId == null ? null : createCorporationId.trim();
    }
}