package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class SsajqkbgbWithBLOBs extends Ssajqkbgb implements Serializable {

    @Override
    public String toString() {
        return "SsajqkbgbWithBLOBs{" +
                "ajjbqkjs='" + ajjbqkjs + '\'' +
                ", anzxjz='" + anzxjz + '\'' +
                ", mqyddwt='" + mqyddwt + '\'' +
                ", jjwtdcs='" + jjwtdcs + '\'' +
                ", dfcqdssclyxgssxw='" + dfcqdssclyxgssxw + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.ajjbqkjs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String ajjbqkjs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.anzxjz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String anzxjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.mqyddwt
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String mqyddwt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.jjwtdcs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String jjwtdcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.dfcqdssclyxgssxw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String dfcqdssclyxgssxw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.ajjbqkjs
     *
     * @return the value of y_ssajqkbgb.ajjbqkjs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getAjjbqkjs() {
        return ajjbqkjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.ajjbqkjs
     *
     * @param ajjbqkjs the value for y_ssajqkbgb.ajjbqkjs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setAjjbqkjs(String ajjbqkjs) {
        this.ajjbqkjs = ajjbqkjs == null ? null : ajjbqkjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.anzxjz
     *
     * @return the value of y_ssajqkbgb.anzxjz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getAnzxjz() {
        return anzxjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.anzxjz
     *
     * @param anzxjz the value for y_ssajqkbgb.anzxjz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setAnzxjz(String anzxjz) {
        this.anzxjz = anzxjz == null ? null : anzxjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.mqyddwt
     *
     * @return the value of y_ssajqkbgb.mqyddwt
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getMqyddwt() {
        return mqyddwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.mqyddwt
     *
     * @param mqyddwt the value for y_ssajqkbgb.mqyddwt
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setMqyddwt(String mqyddwt) {
        this.mqyddwt = mqyddwt == null ? null : mqyddwt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.jjwtdcs
     *
     * @return the value of y_ssajqkbgb.jjwtdcs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getJjwtdcs() {
        return jjwtdcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.jjwtdcs
     *
     * @param jjwtdcs the value for y_ssajqkbgb.jjwtdcs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setJjwtdcs(String jjwtdcs) {
        this.jjwtdcs = jjwtdcs == null ? null : jjwtdcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.dfcqdssclyxgssxw
     *
     * @return the value of y_ssajqkbgb.dfcqdssclyxgssxw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getDfcqdssclyxgssxw() {
        return dfcqdssclyxgssxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.dfcqdssclyxgssxw
     *
     * @param dfcqdssclyxgssxw the value for y_ssajqkbgb.dfcqdssclyxgssxw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setDfcqdssclyxgssxw(String dfcqdssclyxgssxw) {
        this.dfcqdssclyxgssxw = dfcqdssclyxgssxw == null ? null : dfcqdssclyxgssxw.trim();
    }
}