package com.casic.oarp.datavisual.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SsajqkbgbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public SsajqkbgbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZIdIsNull() {
            addCriterion("z_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZIdIsNotNull() {
            addCriterion("z_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZIdEqualTo(String value) {
            addCriterion("z_id_ =", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotEqualTo(String value) {
            addCriterion("z_id_ <>", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThan(String value) {
            addCriterion("z_id_ >", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_id_ >=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThan(String value) {
            addCriterion("z_id_ <", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThanOrEqualTo(String value) {
            addCriterion("z_id_ <=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLike(String value) {
            addCriterion("z_id_ like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotLike(String value) {
            addCriterion("z_id_ not like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdIn(List<String> values) {
            addCriterion("z_id_ in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotIn(List<String> values) {
            addCriterion("z_id_ not in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdBetween(String value1, String value2) {
            addCriterion("z_id_ between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotBetween(String value1, String value2) {
            addCriterion("z_id_ not between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNull() {
            addCriterion("z_createtime_ is null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNotNull() {
            addCriterion("z_createtime_ is not null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeEqualTo(Date value) {
            addCriterion("z_createtime_ =", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotEqualTo(Date value) {
            addCriterion("z_createtime_ <>", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThan(Date value) {
            addCriterion("z_createtime_ >", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ >=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThan(Date value) {
            addCriterion("z_createtime_ <", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ <=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIn(List<Date> values) {
            addCriterion("z_createtime_ in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotIn(List<Date> values) {
            addCriterion("z_createtime_ not in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ not between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNull() {
            addCriterion("z_personnel_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNotNull() {
            addCriterion("z_personnel_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdEqualTo(String value) {
            addCriterion("z_personnel_id_ =", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotEqualTo(String value) {
            addCriterion("z_personnel_id_ <>", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThan(String value) {
            addCriterion("z_personnel_id_ >", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ >=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThan(String value) {
            addCriterion("z_personnel_id_ <", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ <=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLike(String value) {
            addCriterion("z_personnel_id_ like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotLike(String value) {
            addCriterion("z_personnel_id_ not like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIn(List<String> values) {
            addCriterion("z_personnel_id_ in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotIn(List<String> values) {
            addCriterion("z_personnel_id_ not in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ not between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("create_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("create_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("create_user_name =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("create_user_name <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("create_user_name >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_name >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("create_user_name <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("create_user_name <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("create_user_name like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("create_user_name not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("create_user_name in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("create_user_name not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("create_user_name between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("create_user_name not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdIsNull() {
            addCriterion("create_org_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdIsNotNull() {
            addCriterion("create_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdEqualTo(String value) {
            addCriterion("create_org_id =", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdNotEqualTo(String value) {
            addCriterion("create_org_id <>", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdGreaterThan(String value) {
            addCriterion("create_org_id >", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_org_id >=", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdLessThan(String value) {
            addCriterion("create_org_id <", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdLessThanOrEqualTo(String value) {
            addCriterion("create_org_id <=", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdLike(String value) {
            addCriterion("create_org_id like", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdNotLike(String value) {
            addCriterion("create_org_id not like", value, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdIn(List<String> values) {
            addCriterion("create_org_id in", values, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdNotIn(List<String> values) {
            addCriterion("create_org_id not in", values, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdBetween(String value1, String value2) {
            addCriterion("create_org_id between", value1, value2, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIdNotBetween(String value1, String value2) {
            addCriterion("create_org_id not between", value1, value2, "createOrgId");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameIsNull() {
            addCriterion("create_org_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameIsNotNull() {
            addCriterion("create_org_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameEqualTo(String value) {
            addCriterion("create_org_name =", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameNotEqualTo(String value) {
            addCriterion("create_org_name <>", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameGreaterThan(String value) {
            addCriterion("create_org_name >", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_org_name >=", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameLessThan(String value) {
            addCriterion("create_org_name <", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameLessThanOrEqualTo(String value) {
            addCriterion("create_org_name <=", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameLike(String value) {
            addCriterion("create_org_name like", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameNotLike(String value) {
            addCriterion("create_org_name not like", value, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameIn(List<String> values) {
            addCriterion("create_org_name in", values, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameNotIn(List<String> values) {
            addCriterion("create_org_name not in", values, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameBetween(String value1, String value2) {
            addCriterion("create_org_name between", value1, value2, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNameNotBetween(String value1, String value2) {
            addCriterion("create_org_name not between", value1, value2, "createOrgName");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIsNull() {
            addCriterion("closing_time is null");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIsNotNull() {
            addCriterion("closing_time is not null");
            return (Criteria) this;
        }

        public Criteria andClosingTimeEqualTo(Date value) {
            addCriterion("closing_time =", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotEqualTo(Date value) {
            addCriterion("closing_time <>", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeGreaterThan(Date value) {
            addCriterion("closing_time >", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("closing_time >=", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeLessThan(Date value) {
            addCriterion("closing_time <", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeLessThanOrEqualTo(Date value) {
            addCriterion("closing_time <=", value, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeIn(List<Date> values) {
            addCriterion("closing_time in", values, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotIn(List<Date> values) {
            addCriterion("closing_time not in", values, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeBetween(Date value1, Date value2) {
            addCriterion("closing_time between", value1, value2, "closingTime");
            return (Criteria) this;
        }

        public Criteria andClosingTimeNotBetween(Date value1, Date value2) {
            addCriterion("closing_time not between", value1, value2, "closingTime");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNull() {
            addCriterion("secret_level_id is null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNotNull() {
            addCriterion("secret_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdEqualTo(String value) {
            addCriterion("secret_level_id =", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotEqualTo(String value) {
            addCriterion("secret_level_id <>", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThan(String value) {
            addCriterion("secret_level_id >", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThanOrEqualTo(String value) {
            addCriterion("secret_level_id >=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThan(String value) {
            addCriterion("secret_level_id <", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThanOrEqualTo(String value) {
            addCriterion("secret_level_id <=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLike(String value) {
            addCriterion("secret_level_id like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotLike(String value) {
            addCriterion("secret_level_id not like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIn(List<String> values) {
            addCriterion("secret_level_id in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotIn(List<String> values) {
            addCriterion("secret_level_id not in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdBetween(String value1, String value2) {
            addCriterion("secret_level_id between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotBetween(String value1, String value2) {
            addCriterion("secret_level_id not between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSusejdwIsNull() {
            addCriterion("susejdw is null");
            return (Criteria) this;
        }

        public Criteria andSusejdwIsNotNull() {
            addCriterion("susejdw is not null");
            return (Criteria) this;
        }

        public Criteria andSusejdwEqualTo(String value) {
            addCriterion("susejdw =", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwNotEqualTo(String value) {
            addCriterion("susejdw <>", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwGreaterThan(String value) {
            addCriterion("susejdw >", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwGreaterThanOrEqualTo(String value) {
            addCriterion("susejdw >=", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwLessThan(String value) {
            addCriterion("susejdw <", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwLessThanOrEqualTo(String value) {
            addCriterion("susejdw <=", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwLike(String value) {
            addCriterion("susejdw like", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwNotLike(String value) {
            addCriterion("susejdw not like", value, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwIn(List<String> values) {
            addCriterion("susejdw in", values, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwNotIn(List<String> values) {
            addCriterion("susejdw not in", values, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwBetween(String value1, String value2) {
            addCriterion("susejdw between", value1, value2, "susejdw");
            return (Criteria) this;
        }

        public Criteria andSusejdwNotBetween(String value1, String value2) {
            addCriterion("susejdw not between", value1, value2, "susejdw");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNull() {
            addCriterion("case_name is null");
            return (Criteria) this;
        }

        public Criteria andCaseNameIsNotNull() {
            addCriterion("case_name is not null");
            return (Criteria) this;
        }

        public Criteria andCaseNameEqualTo(String value) {
            addCriterion("case_name =", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotEqualTo(String value) {
            addCriterion("case_name <>", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThan(String value) {
            addCriterion("case_name >", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("case_name >=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThan(String value) {
            addCriterion("case_name <", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLessThanOrEqualTo(String value) {
            addCriterion("case_name <=", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameLike(String value) {
            addCriterion("case_name like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotLike(String value) {
            addCriterion("case_name not like", value, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameIn(List<String> values) {
            addCriterion("case_name in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotIn(List<String> values) {
            addCriterion("case_name not in", values, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameBetween(String value1, String value2) {
            addCriterion("case_name between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseNameNotBetween(String value1, String value2) {
            addCriterion("case_name not between", value1, value2, "caseName");
            return (Criteria) this;
        }

        public Criteria andCaseType1IsNull() {
            addCriterion("case_type1 is null");
            return (Criteria) this;
        }

        public Criteria andCaseType1IsNotNull() {
            addCriterion("case_type1 is not null");
            return (Criteria) this;
        }

        public Criteria andCaseType1EqualTo(String value) {
            addCriterion("case_type1 =", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1NotEqualTo(String value) {
            addCriterion("case_type1 <>", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1GreaterThan(String value) {
            addCriterion("case_type1 >", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1GreaterThanOrEqualTo(String value) {
            addCriterion("case_type1 >=", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1LessThan(String value) {
            addCriterion("case_type1 <", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1LessThanOrEqualTo(String value) {
            addCriterion("case_type1 <=", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1Like(String value) {
            addCriterion("case_type1 like", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1NotLike(String value) {
            addCriterion("case_type1 not like", value, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1In(List<String> values) {
            addCriterion("case_type1 in", values, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1NotIn(List<String> values) {
            addCriterion("case_type1 not in", values, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1Between(String value1, String value2) {
            addCriterion("case_type1 between", value1, value2, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType1NotBetween(String value1, String value2) {
            addCriterion("case_type1 not between", value1, value2, "caseType1");
            return (Criteria) this;
        }

        public Criteria andCaseType2IsNull() {
            addCriterion("case_type2 is null");
            return (Criteria) this;
        }

        public Criteria andCaseType2IsNotNull() {
            addCriterion("case_type2 is not null");
            return (Criteria) this;
        }

        public Criteria andCaseType2EqualTo(String value) {
            addCriterion("case_type2 =", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2NotEqualTo(String value) {
            addCriterion("case_type2 <>", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2GreaterThan(String value) {
            addCriterion("case_type2 >", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2GreaterThanOrEqualTo(String value) {
            addCriterion("case_type2 >=", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2LessThan(String value) {
            addCriterion("case_type2 <", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2LessThanOrEqualTo(String value) {
            addCriterion("case_type2 <=", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2Like(String value) {
            addCriterion("case_type2 like", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2NotLike(String value) {
            addCriterion("case_type2 not like", value, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2In(List<String> values) {
            addCriterion("case_type2 in", values, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2NotIn(List<String> values) {
            addCriterion("case_type2 not in", values, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2Between(String value1, String value2) {
            addCriterion("case_type2 between", value1, value2, "caseType2");
            return (Criteria) this;
        }

        public Criteria andCaseType2NotBetween(String value1, String value2) {
            addCriterion("case_type2 not between", value1, value2, "caseType2");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationIsNull() {
            addCriterion("litigation_arbitration is null");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationIsNotNull() {
            addCriterion("litigation_arbitration is not null");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationEqualTo(String value) {
            addCriterion("litigation_arbitration =", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationNotEqualTo(String value) {
            addCriterion("litigation_arbitration <>", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationGreaterThan(String value) {
            addCriterion("litigation_arbitration >", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationGreaterThanOrEqualTo(String value) {
            addCriterion("litigation_arbitration >=", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationLessThan(String value) {
            addCriterion("litigation_arbitration <", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationLessThanOrEqualTo(String value) {
            addCriterion("litigation_arbitration <=", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationLike(String value) {
            addCriterion("litigation_arbitration like", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationNotLike(String value) {
            addCriterion("litigation_arbitration not like", value, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationIn(List<String> values) {
            addCriterion("litigation_arbitration in", values, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationNotIn(List<String> values) {
            addCriterion("litigation_arbitration not in", values, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationBetween(String value1, String value2) {
            addCriterion("litigation_arbitration between", value1, value2, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andLitigationArbitrationNotBetween(String value1, String value2) {
            addCriterion("litigation_arbitration not between", value1, value2, "litigationArbitration");
            return (Criteria) this;
        }

        public Criteria andProsecutionIsNull() {
            addCriterion("prosecution is null");
            return (Criteria) this;
        }

        public Criteria andProsecutionIsNotNull() {
            addCriterion("prosecution is not null");
            return (Criteria) this;
        }

        public Criteria andProsecutionEqualTo(String value) {
            addCriterion("prosecution =", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionNotEqualTo(String value) {
            addCriterion("prosecution <>", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionGreaterThan(String value) {
            addCriterion("prosecution >", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionGreaterThanOrEqualTo(String value) {
            addCriterion("prosecution >=", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionLessThan(String value) {
            addCriterion("prosecution <", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionLessThanOrEqualTo(String value) {
            addCriterion("prosecution <=", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionLike(String value) {
            addCriterion("prosecution like", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionNotLike(String value) {
            addCriterion("prosecution not like", value, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionIn(List<String> values) {
            addCriterion("prosecution in", values, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionNotIn(List<String> values) {
            addCriterion("prosecution not in", values, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionBetween(String value1, String value2) {
            addCriterion("prosecution between", value1, value2, "prosecution");
            return (Criteria) this;
        }

        public Criteria andProsecutionNotBetween(String value1, String value2) {
            addCriterion("prosecution not between", value1, value2, "prosecution");
            return (Criteria) this;
        }

        public Criteria andScjdIsNull() {
            addCriterion("scjd is null");
            return (Criteria) this;
        }

        public Criteria andScjdIsNotNull() {
            addCriterion("scjd is not null");
            return (Criteria) this;
        }

        public Criteria andScjdEqualTo(String value) {
            addCriterion("scjd =", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdNotEqualTo(String value) {
            addCriterion("scjd <>", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdGreaterThan(String value) {
            addCriterion("scjd >", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdGreaterThanOrEqualTo(String value) {
            addCriterion("scjd >=", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdLessThan(String value) {
            addCriterion("scjd <", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdLessThanOrEqualTo(String value) {
            addCriterion("scjd <=", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdLike(String value) {
            addCriterion("scjd like", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdNotLike(String value) {
            addCriterion("scjd not like", value, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdIn(List<String> values) {
            addCriterion("scjd in", values, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdNotIn(List<String> values) {
            addCriterion("scjd not in", values, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdBetween(String value1, String value2) {
            addCriterion("scjd between", value1, value2, "scjd");
            return (Criteria) this;
        }

        public Criteria andScjdNotBetween(String value1, String value2) {
            addCriterion("scjd not between", value1, value2, "scjd");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgIsNull() {
            addCriterion("mqjbsfjg is null");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgIsNotNull() {
            addCriterion("mqjbsfjg is not null");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgEqualTo(String value) {
            addCriterion("mqjbsfjg =", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgNotEqualTo(String value) {
            addCriterion("mqjbsfjg <>", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgGreaterThan(String value) {
            addCriterion("mqjbsfjg >", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgGreaterThanOrEqualTo(String value) {
            addCriterion("mqjbsfjg >=", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgLessThan(String value) {
            addCriterion("mqjbsfjg <", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgLessThanOrEqualTo(String value) {
            addCriterion("mqjbsfjg <=", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgLike(String value) {
            addCriterion("mqjbsfjg like", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgNotLike(String value) {
            addCriterion("mqjbsfjg not like", value, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgIn(List<String> values) {
            addCriterion("mqjbsfjg in", values, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgNotIn(List<String> values) {
            addCriterion("mqjbsfjg not in", values, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgBetween(String value1, String value2) {
            addCriterion("mqjbsfjg between", value1, value2, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andMqjbsfjgNotBetween(String value1, String value2) {
            addCriterion("mqjbsfjg not between", value1, value2, "mqjbsfjg");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateIsNull() {
            addCriterion("prosecution_date is null");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateIsNotNull() {
            addCriterion("prosecution_date is not null");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateEqualTo(Date value) {
            addCriterion("prosecution_date =", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateNotEqualTo(Date value) {
            addCriterion("prosecution_date <>", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateGreaterThan(Date value) {
            addCriterion("prosecution_date >", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("prosecution_date >=", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateLessThan(Date value) {
            addCriterion("prosecution_date <", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateLessThanOrEqualTo(Date value) {
            addCriterion("prosecution_date <=", value, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateIn(List<Date> values) {
            addCriterion("prosecution_date in", values, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateNotIn(List<Date> values) {
            addCriterion("prosecution_date not in", values, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateBetween(Date value1, Date value2) {
            addCriterion("prosecution_date between", value1, value2, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andProsecutionDateNotBetween(Date value1, Date value2) {
            addCriterion("prosecution_date not between", value1, value2, "prosecutionDate");
            return (Criteria) this;
        }

        public Criteria andBqysadwIsNull() {
            addCriterion("bqysadw is null");
            return (Criteria) this;
        }

        public Criteria andBqysadwIsNotNull() {
            addCriterion("bqysadw is not null");
            return (Criteria) this;
        }

        public Criteria andBqysadwEqualTo(String value) {
            addCriterion("bqysadw =", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwNotEqualTo(String value) {
            addCriterion("bqysadw <>", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwGreaterThan(String value) {
            addCriterion("bqysadw >", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwGreaterThanOrEqualTo(String value) {
            addCriterion("bqysadw >=", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwLessThan(String value) {
            addCriterion("bqysadw <", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwLessThanOrEqualTo(String value) {
            addCriterion("bqysadw <=", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwLike(String value) {
            addCriterion("bqysadw like", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwNotLike(String value) {
            addCriterion("bqysadw not like", value, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwIn(List<String> values) {
            addCriterion("bqysadw in", values, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwNotIn(List<String> values) {
            addCriterion("bqysadw not in", values, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwBetween(String value1, String value2) {
            addCriterion("bqysadw between", value1, value2, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andBqysadwNotBetween(String value1, String value2) {
            addCriterion("bqysadw not between", value1, value2, "bqysadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwIsNull() {
            addCriterion("dfsadw is null");
            return (Criteria) this;
        }

        public Criteria andDfsadwIsNotNull() {
            addCriterion("dfsadw is not null");
            return (Criteria) this;
        }

        public Criteria andDfsadwEqualTo(String value) {
            addCriterion("dfsadw =", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwNotEqualTo(String value) {
            addCriterion("dfsadw <>", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwGreaterThan(String value) {
            addCriterion("dfsadw >", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwGreaterThanOrEqualTo(String value) {
            addCriterion("dfsadw >=", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwLessThan(String value) {
            addCriterion("dfsadw <", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwLessThanOrEqualTo(String value) {
            addCriterion("dfsadw <=", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwLike(String value) {
            addCriterion("dfsadw like", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwNotLike(String value) {
            addCriterion("dfsadw not like", value, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwIn(List<String> values) {
            addCriterion("dfsadw in", values, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwNotIn(List<String> values) {
            addCriterion("dfsadw not in", values, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwBetween(String value1, String value2) {
            addCriterion("dfsadw between", value1, value2, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfsadwNotBetween(String value1, String value2) {
            addCriterion("dfsadw not between", value1, value2, "dfsadw");
            return (Criteria) this;
        }

        public Criteria andDfdwxzIsNull() {
            addCriterion("dfdwxz is null");
            return (Criteria) this;
        }

        public Criteria andDfdwxzIsNotNull() {
            addCriterion("dfdwxz is not null");
            return (Criteria) this;
        }

        public Criteria andDfdwxzEqualTo(String value) {
            addCriterion("dfdwxz =", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzNotEqualTo(String value) {
            addCriterion("dfdwxz <>", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzGreaterThan(String value) {
            addCriterion("dfdwxz >", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzGreaterThanOrEqualTo(String value) {
            addCriterion("dfdwxz >=", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzLessThan(String value) {
            addCriterion("dfdwxz <", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzLessThanOrEqualTo(String value) {
            addCriterion("dfdwxz <=", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzLike(String value) {
            addCriterion("dfdwxz like", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzNotLike(String value) {
            addCriterion("dfdwxz not like", value, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzIn(List<String> values) {
            addCriterion("dfdwxz in", values, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzNotIn(List<String> values) {
            addCriterion("dfdwxz not in", values, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzBetween(String value1, String value2) {
            addCriterion("dfdwxz between", value1, value2, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andDfdwxzNotBetween(String value1, String value2) {
            addCriterion("dfdwxz not between", value1, value2, "dfdwxz");
            return (Criteria) this;
        }

        public Criteria andBdjeIsNull() {
            addCriterion("bdje is null");
            return (Criteria) this;
        }

        public Criteria andBdjeIsNotNull() {
            addCriterion("bdje is not null");
            return (Criteria) this;
        }

        public Criteria andBdjeEqualTo(BigDecimal value) {
            addCriterion("bdje =", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeNotEqualTo(BigDecimal value) {
            addCriterion("bdje <>", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeGreaterThan(BigDecimal value) {
            addCriterion("bdje >", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bdje >=", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeLessThan(BigDecimal value) {
            addCriterion("bdje <", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bdje <=", value, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeIn(List<BigDecimal> values) {
            addCriterion("bdje in", values, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeNotIn(List<BigDecimal> values) {
            addCriterion("bdje not in", values, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bdje between", value1, value2, "bdje");
            return (Criteria) this;
        }

        public Criteria andBdjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bdje not between", value1, value2, "bdje");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblIsNull() {
            addCriterion("byxz_byja_zzbl is null");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblIsNotNull() {
            addCriterion("byxz_byja_zzbl is not null");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblEqualTo(String value) {
            addCriterion("byxz_byja_zzbl =", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblNotEqualTo(String value) {
            addCriterion("byxz_byja_zzbl <>", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblGreaterThan(String value) {
            addCriterion("byxz_byja_zzbl >", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblGreaterThanOrEqualTo(String value) {
            addCriterion("byxz_byja_zzbl >=", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblLessThan(String value) {
            addCriterion("byxz_byja_zzbl <", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblLessThanOrEqualTo(String value) {
            addCriterion("byxz_byja_zzbl <=", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblLike(String value) {
            addCriterion("byxz_byja_zzbl like", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblNotLike(String value) {
            addCriterion("byxz_byja_zzbl not like", value, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblIn(List<String> values) {
            addCriterion("byxz_byja_zzbl in", values, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblNotIn(List<String> values) {
            addCriterion("byxz_byja_zzbl not in", values, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblBetween(String value1, String value2) {
            addCriterion("byxz_byja_zzbl between", value1, value2, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andByxzByjaZzblNotBetween(String value1, String value2) {
            addCriterion("byxz_byja_zzbl not between", value1, value2, "byxzByjaZzbl");
            return (Criteria) this;
        }

        public Criteria andBeizIsNull() {
            addCriterion("beiz is null");
            return (Criteria) this;
        }

        public Criteria andBeizIsNotNull() {
            addCriterion("beiz is not null");
            return (Criteria) this;
        }

        public Criteria andBeizEqualTo(String value) {
            addCriterion("beiz =", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizNotEqualTo(String value) {
            addCriterion("beiz <>", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizGreaterThan(String value) {
            addCriterion("beiz >", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizGreaterThanOrEqualTo(String value) {
            addCriterion("beiz >=", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizLessThan(String value) {
            addCriterion("beiz <", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizLessThanOrEqualTo(String value) {
            addCriterion("beiz <=", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizLike(String value) {
            addCriterion("beiz like", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizNotLike(String value) {
            addCriterion("beiz not like", value, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizIn(List<String> values) {
            addCriterion("beiz in", values, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizNotIn(List<String> values) {
            addCriterion("beiz not in", values, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizBetween(String value1, String value2) {
            addCriterion("beiz between", value1, value2, "beiz");
            return (Criteria) this;
        }

        public Criteria andBeizNotBetween(String value1, String value2) {
            addCriterion("beiz not between", value1, value2, "beiz");
            return (Criteria) this;
        }

        public Criteria andMonthRecordIsNull() {
            addCriterion("month_record is null");
            return (Criteria) this;
        }

        public Criteria andMonthRecordIsNotNull() {
            addCriterion("month_record is not null");
            return (Criteria) this;
        }

        public Criteria andMonthRecordEqualTo(String value) {
            addCriterion("month_record =", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordNotEqualTo(String value) {
            addCriterion("month_record <>", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordGreaterThan(String value) {
            addCriterion("month_record >", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordGreaterThanOrEqualTo(String value) {
            addCriterion("month_record >=", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordLessThan(String value) {
            addCriterion("month_record <", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordLessThanOrEqualTo(String value) {
            addCriterion("month_record <=", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordLike(String value) {
            addCriterion("month_record like", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordNotLike(String value) {
            addCriterion("month_record not like", value, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordIn(List<String> values) {
            addCriterion("month_record in", values, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordNotIn(List<String> values) {
            addCriterion("month_record not in", values, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordBetween(String value1, String value2) {
            addCriterion("month_record between", value1, value2, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMonthRecordNotBetween(String value1, String value2) {
            addCriterion("month_record not between", value1, value2, "monthRecord");
            return (Criteria) this;
        }

        public Criteria andMarkingIsNull() {
            addCriterion("marking is null");
            return (Criteria) this;
        }

        public Criteria andMarkingIsNotNull() {
            addCriterion("marking is not null");
            return (Criteria) this;
        }

        public Criteria andMarkingEqualTo(String value) {
            addCriterion("marking =", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingNotEqualTo(String value) {
            addCriterion("marking <>", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingGreaterThan(String value) {
            addCriterion("marking >", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingGreaterThanOrEqualTo(String value) {
            addCriterion("marking >=", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingLessThan(String value) {
            addCriterion("marking <", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingLessThanOrEqualTo(String value) {
            addCriterion("marking <=", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingLike(String value) {
            addCriterion("marking like", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingNotLike(String value) {
            addCriterion("marking not like", value, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingIn(List<String> values) {
            addCriterion("marking in", values, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingNotIn(List<String> values) {
            addCriterion("marking not in", values, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingBetween(String value1, String value2) {
            addCriterion("marking between", value1, value2, "marking");
            return (Criteria) this;
        }

        public Criteria andMarkingNotBetween(String value1, String value2) {
            addCriterion("marking not between", value1, value2, "marking");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time_ =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time_ <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time_ >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time_ >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time_ <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time_ <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time_ in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time_ not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time_ between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time_ not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSjljjeIsNull() {
            addCriterion("sjljje is null");
            return (Criteria) this;
        }

        public Criteria andSjljjeIsNotNull() {
            addCriterion("sjljje is not null");
            return (Criteria) this;
        }

        public Criteria andSjljjeEqualTo(BigDecimal value) {
            addCriterion("sjljje =", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeNotEqualTo(BigDecimal value) {
            addCriterion("sjljje <>", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeGreaterThan(BigDecimal value) {
            addCriterion("sjljje >", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sjljje >=", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeLessThan(BigDecimal value) {
            addCriterion("sjljje <", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sjljje <=", value, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeIn(List<BigDecimal> values) {
            addCriterion("sjljje in", values, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeNotIn(List<BigDecimal> values) {
            addCriterion("sjljje not in", values, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sjljje between", value1, value2, "sjljje");
            return (Criteria) this;
        }

        public Criteria andSjljjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sjljje not between", value1, value2, "sjljje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeIsNull() {
            addCriterion("whjjssje is null");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeIsNotNull() {
            addCriterion("whjjssje is not null");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeEqualTo(BigDecimal value) {
            addCriterion("whjjssje =", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeNotEqualTo(BigDecimal value) {
            addCriterion("whjjssje <>", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeGreaterThan(BigDecimal value) {
            addCriterion("whjjssje >", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("whjjssje >=", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeLessThan(BigDecimal value) {
            addCriterion("whjjssje <", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("whjjssje <=", value, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeIn(List<BigDecimal> values) {
            addCriterion("whjjssje in", values, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeNotIn(List<BigDecimal> values) {
            addCriterion("whjjssje not in", values, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("whjjssje between", value1, value2, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andWhjjssjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("whjjssje not between", value1, value2, "whjjssje");
            return (Criteria) this;
        }

        public Criteria andHjljjeIsNull() {
            addCriterion("hjljje is null");
            return (Criteria) this;
        }

        public Criteria andHjljjeIsNotNull() {
            addCriterion("hjljje is not null");
            return (Criteria) this;
        }

        public Criteria andHjljjeEqualTo(BigDecimal value) {
            addCriterion("hjljje =", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeNotEqualTo(BigDecimal value) {
            addCriterion("hjljje <>", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeGreaterThan(BigDecimal value) {
            addCriterion("hjljje >", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hjljje >=", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeLessThan(BigDecimal value) {
            addCriterion("hjljje <", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hjljje <=", value, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeIn(List<BigDecimal> values) {
            addCriterion("hjljje in", values, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeNotIn(List<BigDecimal> values) {
            addCriterion("hjljje not in", values, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hjljje between", value1, value2, "hjljje");
            return (Criteria) this;
        }

        public Criteria andHjljjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hjljje not between", value1, value2, "hjljje");
            return (Criteria) this;
        }

        public Criteria andJafsIsNull() {
            addCriterion("jafs is null");
            return (Criteria) this;
        }

        public Criteria andJafsIsNotNull() {
            addCriterion("jafs is not null");
            return (Criteria) this;
        }

        public Criteria andJafsEqualTo(String value) {
            addCriterion("jafs =", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotEqualTo(String value) {
            addCriterion("jafs <>", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsGreaterThan(String value) {
            addCriterion("jafs >", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsGreaterThanOrEqualTo(String value) {
            addCriterion("jafs >=", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLessThan(String value) {
            addCriterion("jafs <", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLessThanOrEqualTo(String value) {
            addCriterion("jafs <=", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsLike(String value) {
            addCriterion("jafs like", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotLike(String value) {
            addCriterion("jafs not like", value, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsIn(List<String> values) {
            addCriterion("jafs in", values, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotIn(List<String> values) {
            addCriterion("jafs not in", values, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsBetween(String value1, String value2) {
            addCriterion("jafs between", value1, value2, "jafs");
            return (Criteria) this;
        }

        public Criteria andJafsNotBetween(String value1, String value2) {
            addCriterion("jafs not between", value1, value2, "jafs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 09 13:22:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}