package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Ssajqkbgb implements Serializable {

    @Override
    public String toString() {
        return "Ssajqkbgb{" +
                "zId='" + zId + '\'' +
                ", zCreatetime=" + zCreatetime +
                ", zPersonnelId='" + zPersonnelId + '\'' +
                ", createUserName='" + createUserName + '\'' +
                ", createOrgId='" + createOrgId + '\'' +
                ", createOrgName='" + createOrgName + '\'' +
                ", closingTime=" + closingTime +
                ", secretLevelId='" + secretLevelId + '\'' +
                ", susejdw='" + susejdw + '\'' +
                ", caseName='" + caseName + '\'' +
                ", caseType1='" + caseType1 + '\'' +
                ", caseType2='" + caseType2 + '\'' +
                ", litigationArbitration='" + litigationArbitration + '\'' +
                ", prosecution='" + prosecution + '\'' +
                ", scjd='" + scjd + '\'' +
                ", mqjbsfjg='" + mqjbsfjg + '\'' +
                ", prosecutionDate=" + prosecutionDate +
                ", bqysadw='" + bqysadw + '\'' +
                ", dfsadw='" + dfsadw + '\'' +
                ", dfdwxz='" + dfdwxz + '\'' +
                ", bdje=" + bdje +
                ", byxzByjaZzbl='" + byxzByjaZzbl + '\'' +
                ", beiz='" + beiz + '\'' +
                ", monthRecord='" + monthRecord + '\'' +
                ", marking='" + marking + '\'' +
                ", updateTime=" + updateTime +
                ", sjljje=" + sjljje +
                ", whjjssje=" + whjjssje +
                ", hjljje=" + hjljje +
                ", jafs='" + jafs + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.z_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String zId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.z_createtime_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private Date zCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.z_personnel_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String zPersonnelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.create_user_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.create_org_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String createOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.create_org_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String createOrgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.closing_time
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private Date closingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.secret_level_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String secretLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.susejdw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String susejdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.case_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.case_type1
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String caseType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.case_type2
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String caseType2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.litigation_arbitration
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String litigationArbitration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.prosecution
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String prosecution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.scjd
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String scjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.mqjbsfjg
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String mqjbsfjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.prosecution_date
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private Date prosecutionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.bqysadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String bqysadw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.dfsadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String dfsadw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.dfdwxz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String dfdwxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.bdje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private BigDecimal bdje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.byxz_byja_zzbl
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String byxzByjaZzbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.beiz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String beiz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.month_record
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String monthRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.marking
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String marking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.update_time_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.sjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private BigDecimal sjljje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.whjjssje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private BigDecimal whjjssje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.hjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private BigDecimal hjljje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_ssajqkbgb.jafs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private String jafs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_ssajqkbgb
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.z_id_
     *
     * @return the value of y_ssajqkbgb.z_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getzId() {
        return zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.z_id_
     *
     * @param zId the value for y_ssajqkbgb.z_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setzId(String zId) {
        this.zId = zId == null ? null : zId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.z_createtime_
     *
     * @return the value of y_ssajqkbgb.z_createtime_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Date getzCreatetime() {
        return zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.z_createtime_
     *
     * @param zCreatetime the value for y_ssajqkbgb.z_createtime_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setzCreatetime(Date zCreatetime) {
        this.zCreatetime = zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.z_personnel_id_
     *
     * @return the value of y_ssajqkbgb.z_personnel_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getzPersonnelId() {
        return zPersonnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.z_personnel_id_
     *
     * @param zPersonnelId the value for y_ssajqkbgb.z_personnel_id_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setzPersonnelId(String zPersonnelId) {
        this.zPersonnelId = zPersonnelId == null ? null : zPersonnelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.create_user_name
     *
     * @return the value of y_ssajqkbgb.create_user_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.create_user_name
     *
     * @param createUserName the value for y_ssajqkbgb.create_user_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.create_org_id
     *
     * @return the value of y_ssajqkbgb.create_org_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCreateOrgId() {
        return createOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.create_org_id
     *
     * @param createOrgId the value for y_ssajqkbgb.create_org_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCreateOrgId(String createOrgId) {
        this.createOrgId = createOrgId == null ? null : createOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.create_org_name
     *
     * @return the value of y_ssajqkbgb.create_org_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCreateOrgName() {
        return createOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.create_org_name
     *
     * @param createOrgName the value for y_ssajqkbgb.create_org_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCreateOrgName(String createOrgName) {
        this.createOrgName = createOrgName == null ? null : createOrgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.closing_time
     *
     * @return the value of y_ssajqkbgb.closing_time
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Date getClosingTime() {
        return closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.closing_time
     *
     * @param closingTime the value for y_ssajqkbgb.closing_time
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setClosingTime(Date closingTime) {
        this.closingTime = closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.secret_level_id
     *
     * @return the value of y_ssajqkbgb.secret_level_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getSecretLevelId() {
        return secretLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.secret_level_id
     *
     * @param secretLevelId the value for y_ssajqkbgb.secret_level_id
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setSecretLevelId(String secretLevelId) {
        this.secretLevelId = secretLevelId == null ? null : secretLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.susejdw
     *
     * @return the value of y_ssajqkbgb.susejdw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getSusejdw() {
        return susejdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.susejdw
     *
     * @param susejdw the value for y_ssajqkbgb.susejdw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setSusejdw(String susejdw) {
        this.susejdw = susejdw == null ? null : susejdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.case_name
     *
     * @return the value of y_ssajqkbgb.case_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.case_name
     *
     * @param caseName the value for y_ssajqkbgb.case_name
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.case_type1
     *
     * @return the value of y_ssajqkbgb.case_type1
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCaseType1() {
        return caseType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.case_type1
     *
     * @param caseType1 the value for y_ssajqkbgb.case_type1
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCaseType1(String caseType1) {
        this.caseType1 = caseType1 == null ? null : caseType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.case_type2
     *
     * @return the value of y_ssajqkbgb.case_type2
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getCaseType2() {
        return caseType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.case_type2
     *
     * @param caseType2 the value for y_ssajqkbgb.case_type2
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setCaseType2(String caseType2) {
        this.caseType2 = caseType2 == null ? null : caseType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.litigation_arbitration
     *
     * @return the value of y_ssajqkbgb.litigation_arbitration
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getLitigationArbitration() {
        return litigationArbitration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.litigation_arbitration
     *
     * @param litigationArbitration the value for y_ssajqkbgb.litigation_arbitration
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setLitigationArbitration(String litigationArbitration) {
        this.litigationArbitration = litigationArbitration == null ? null : litigationArbitration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.prosecution
     *
     * @return the value of y_ssajqkbgb.prosecution
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getProsecution() {
        return prosecution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.prosecution
     *
     * @param prosecution the value for y_ssajqkbgb.prosecution
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setProsecution(String prosecution) {
        this.prosecution = prosecution == null ? null : prosecution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.scjd
     *
     * @return the value of y_ssajqkbgb.scjd
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getScjd() {
        return scjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.scjd
     *
     * @param scjd the value for y_ssajqkbgb.scjd
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setScjd(String scjd) {
        this.scjd = scjd == null ? null : scjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.mqjbsfjg
     *
     * @return the value of y_ssajqkbgb.mqjbsfjg
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getMqjbsfjg() {
        return mqjbsfjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.mqjbsfjg
     *
     * @param mqjbsfjg the value for y_ssajqkbgb.mqjbsfjg
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setMqjbsfjg(String mqjbsfjg) {
        this.mqjbsfjg = mqjbsfjg == null ? null : mqjbsfjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.prosecution_date
     *
     * @return the value of y_ssajqkbgb.prosecution_date
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Date getProsecutionDate() {
        return prosecutionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.prosecution_date
     *
     * @param prosecutionDate the value for y_ssajqkbgb.prosecution_date
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setProsecutionDate(Date prosecutionDate) {
        this.prosecutionDate = prosecutionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.bqysadw
     *
     * @return the value of y_ssajqkbgb.bqysadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getBqysadw() {
        return bqysadw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.bqysadw
     *
     * @param bqysadw the value for y_ssajqkbgb.bqysadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setBqysadw(String bqysadw) {
        this.bqysadw = bqysadw == null ? null : bqysadw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.dfsadw
     *
     * @return the value of y_ssajqkbgb.dfsadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getDfsadw() {
        return dfsadw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.dfsadw
     *
     * @param dfsadw the value for y_ssajqkbgb.dfsadw
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setDfsadw(String dfsadw) {
        this.dfsadw = dfsadw == null ? null : dfsadw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.dfdwxz
     *
     * @return the value of y_ssajqkbgb.dfdwxz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getDfdwxz() {
        return dfdwxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.dfdwxz
     *
     * @param dfdwxz the value for y_ssajqkbgb.dfdwxz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setDfdwxz(String dfdwxz) {
        this.dfdwxz = dfdwxz == null ? null : dfdwxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.bdje
     *
     * @return the value of y_ssajqkbgb.bdje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public BigDecimal getBdje() {
        return bdje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.bdje
     *
     * @param bdje the value for y_ssajqkbgb.bdje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setBdje(BigDecimal bdje) {
        this.bdje = bdje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.byxz_byja_zzbl
     *
     * @return the value of y_ssajqkbgb.byxz_byja_zzbl
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getByxzByjaZzbl() {
        return byxzByjaZzbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.byxz_byja_zzbl
     *
     * @param byxzByjaZzbl the value for y_ssajqkbgb.byxz_byja_zzbl
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setByxzByjaZzbl(String byxzByjaZzbl) {
        this.byxzByjaZzbl = byxzByjaZzbl == null ? null : byxzByjaZzbl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.beiz
     *
     * @return the value of y_ssajqkbgb.beiz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getBeiz() {
        return beiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.beiz
     *
     * @param beiz the value for y_ssajqkbgb.beiz
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setBeiz(String beiz) {
        this.beiz = beiz == null ? null : beiz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.month_record
     *
     * @return the value of y_ssajqkbgb.month_record
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getMonthRecord() {
        return monthRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.month_record
     *
     * @param monthRecord the value for y_ssajqkbgb.month_record
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setMonthRecord(String monthRecord) {
        this.monthRecord = monthRecord == null ? null : monthRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.marking
     *
     * @return the value of y_ssajqkbgb.marking
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getMarking() {
        return marking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.marking
     *
     * @param marking the value for y_ssajqkbgb.marking
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setMarking(String marking) {
        this.marking = marking == null ? null : marking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.update_time_
     *
     * @return the value of y_ssajqkbgb.update_time_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.update_time_
     *
     * @param updateTime the value for y_ssajqkbgb.update_time_
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.sjljje
     *
     * @return the value of y_ssajqkbgb.sjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public BigDecimal getSjljje() {
        return sjljje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.sjljje
     *
     * @param sjljje the value for y_ssajqkbgb.sjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setSjljje(BigDecimal sjljje) {
        this.sjljje = sjljje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.whjjssje
     *
     * @return the value of y_ssajqkbgb.whjjssje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public BigDecimal getWhjjssje() {
        return whjjssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.whjjssje
     *
     * @param whjjssje the value for y_ssajqkbgb.whjjssje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setWhjjssje(BigDecimal whjjssje) {
        this.whjjssje = whjjssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.hjljje
     *
     * @return the value of y_ssajqkbgb.hjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public BigDecimal getHjljje() {
        return hjljje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.hjljje
     *
     * @param hjljje the value for y_ssajqkbgb.hjljje
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setHjljje(BigDecimal hjljje) {
        this.hjljje = hjljje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_ssajqkbgb.jafs
     *
     * @return the value of y_ssajqkbgb.jafs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public String getJafs() {
        return jafs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_ssajqkbgb.jafs
     *
     * @param jafs the value for y_ssajqkbgb.jafs
     *
     * @mbg.generated Mon Jul 09 13:22:16 CST 2018
     */
    public void setJafs(String jafs) {
        this.jafs = jafs == null ? null : jafs.trim();
    }
}