package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Zhongdjcfxpgtj implements Serializable {

    @Override
    public String toString() {
        return "Zhongdjcfxpgtj{" +
                "zId='" + zId + '\'' +
                ", erjdwmc='" + erjdwmc + '\'' +
                ", sanjhsjdwmc='" + sanjhsjdwmc + '\'' +
                ", shenysxmc='" + shenysxmc + '\'' +
                ", shixlx='" + shixlx + '\'' +
                ", zuizsydwjc='" + zuizsydwjc + '\'' +
                ", shenyjg='" + shenyjg + '\'' +
                ", shenysj=" + shenysj +
                ", zhuzbm='" + zhuzbm + '\'' +
                ", fengxpgsfbghzp='" + fengxpgsfbghzp + '\'' +
                ", shixfxcd='" + shixfxcd + '\'' +
                ", cainqk='" + cainqk + '\'' +
                ", remark='" + remark + '\'' +
                ", zCreatetime=" + zCreatetime +
                ", zPersonnelId='" + zPersonnelId + '\'' +
                ", secretLevelId='" + secretLevelId + '\'' +
                ", shejje=" + shejje +
                ", shixms='" + shixms + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.z_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String zId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.erjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String erjdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.sanjhsjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String sanjhsjdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shenysxmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String shenysxmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shixlx
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String shixlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.zuizsydwjc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String zuizsydwjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shenyjg
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String shenyjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shenysj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private Date shenysj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.zhuzbm
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String zhuzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.fengxpgsfbghzp
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String fengxpgsfbghzp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shixfxcd
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String shixfxcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.cainqk
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String cainqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.remark
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.z_createtime_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private Date zCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.z_personnel_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String zPersonnelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.secret_level_id
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String secretLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shejje
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private BigDecimal shejje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_zhongdjcfxpgtj.shixms
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private String shixms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.z_id_
     *
     * @return the value of y_zhongdjcfxpgtj.z_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getzId() {
        return zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.z_id_
     *
     * @param zId the value for y_zhongdjcfxpgtj.z_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setzId(String zId) {
        this.zId = zId == null ? null : zId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.erjdwmc
     *
     * @return the value of y_zhongdjcfxpgtj.erjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getErjdwmc() {
        return erjdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.erjdwmc
     *
     * @param erjdwmc the value for y_zhongdjcfxpgtj.erjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setErjdwmc(String erjdwmc) {
        this.erjdwmc = erjdwmc == null ? null : erjdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.sanjhsjdwmc
     *
     * @return the value of y_zhongdjcfxpgtj.sanjhsjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getSanjhsjdwmc() {
        return sanjhsjdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.sanjhsjdwmc
     *
     * @param sanjhsjdwmc the value for y_zhongdjcfxpgtj.sanjhsjdwmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setSanjhsjdwmc(String sanjhsjdwmc) {
        this.sanjhsjdwmc = sanjhsjdwmc == null ? null : sanjhsjdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shenysxmc
     *
     * @return the value of y_zhongdjcfxpgtj.shenysxmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getShenysxmc() {
        return shenysxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shenysxmc
     *
     * @param shenysxmc the value for y_zhongdjcfxpgtj.shenysxmc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShenysxmc(String shenysxmc) {
        this.shenysxmc = shenysxmc == null ? null : shenysxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shixlx
     *
     * @return the value of y_zhongdjcfxpgtj.shixlx
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getShixlx() {
        return shixlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shixlx
     *
     * @param shixlx the value for y_zhongdjcfxpgtj.shixlx
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShixlx(String shixlx) {
        this.shixlx = shixlx == null ? null : shixlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.zuizsydwjc
     *
     * @return the value of y_zhongdjcfxpgtj.zuizsydwjc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getZuizsydwjc() {
        return zuizsydwjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.zuizsydwjc
     *
     * @param zuizsydwjc the value for y_zhongdjcfxpgtj.zuizsydwjc
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setZuizsydwjc(String zuizsydwjc) {
        this.zuizsydwjc = zuizsydwjc == null ? null : zuizsydwjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shenyjg
     *
     * @return the value of y_zhongdjcfxpgtj.shenyjg
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getShenyjg() {
        return shenyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shenyjg
     *
     * @param shenyjg the value for y_zhongdjcfxpgtj.shenyjg
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShenyjg(String shenyjg) {
        this.shenyjg = shenyjg == null ? null : shenyjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shenysj
     *
     * @return the value of y_zhongdjcfxpgtj.shenysj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public Date getShenysj() {
        return shenysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shenysj
     *
     * @param shenysj the value for y_zhongdjcfxpgtj.shenysj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShenysj(Date shenysj) {
        this.shenysj = shenysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.zhuzbm
     *
     * @return the value of y_zhongdjcfxpgtj.zhuzbm
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getZhuzbm() {
        return zhuzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.zhuzbm
     *
     * @param zhuzbm the value for y_zhongdjcfxpgtj.zhuzbm
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setZhuzbm(String zhuzbm) {
        this.zhuzbm = zhuzbm == null ? null : zhuzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.fengxpgsfbghzp
     *
     * @return the value of y_zhongdjcfxpgtj.fengxpgsfbghzp
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getFengxpgsfbghzp() {
        return fengxpgsfbghzp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.fengxpgsfbghzp
     *
     * @param fengxpgsfbghzp the value for y_zhongdjcfxpgtj.fengxpgsfbghzp
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setFengxpgsfbghzp(String fengxpgsfbghzp) {
        this.fengxpgsfbghzp = fengxpgsfbghzp == null ? null : fengxpgsfbghzp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shixfxcd
     *
     * @return the value of y_zhongdjcfxpgtj.shixfxcd
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getShixfxcd() {
        return shixfxcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shixfxcd
     *
     * @param shixfxcd the value for y_zhongdjcfxpgtj.shixfxcd
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShixfxcd(String shixfxcd) {
        this.shixfxcd = shixfxcd == null ? null : shixfxcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.cainqk
     *
     * @return the value of y_zhongdjcfxpgtj.cainqk
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getCainqk() {
        return cainqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.cainqk
     *
     * @param cainqk the value for y_zhongdjcfxpgtj.cainqk
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setCainqk(String cainqk) {
        this.cainqk = cainqk == null ? null : cainqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.remark
     *
     * @return the value of y_zhongdjcfxpgtj.remark
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.remark
     *
     * @param remark the value for y_zhongdjcfxpgtj.remark
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.z_createtime_
     *
     * @return the value of y_zhongdjcfxpgtj.z_createtime_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public Date getzCreatetime() {
        return zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.z_createtime_
     *
     * @param zCreatetime the value for y_zhongdjcfxpgtj.z_createtime_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setzCreatetime(Date zCreatetime) {
        this.zCreatetime = zCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.z_personnel_id_
     *
     * @return the value of y_zhongdjcfxpgtj.z_personnel_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getzPersonnelId() {
        return zPersonnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.z_personnel_id_
     *
     * @param zPersonnelId the value for y_zhongdjcfxpgtj.z_personnel_id_
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setzPersonnelId(String zPersonnelId) {
        this.zPersonnelId = zPersonnelId == null ? null : zPersonnelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.secret_level_id
     *
     * @return the value of y_zhongdjcfxpgtj.secret_level_id
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getSecretLevelId() {
        return secretLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.secret_level_id
     *
     * @param secretLevelId the value for y_zhongdjcfxpgtj.secret_level_id
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setSecretLevelId(String secretLevelId) {
        this.secretLevelId = secretLevelId == null ? null : secretLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shejje
     *
     * @return the value of y_zhongdjcfxpgtj.shejje
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public BigDecimal getShejje() {
        return shejje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shejje
     *
     * @param shejje the value for y_zhongdjcfxpgtj.shejje
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShejje(BigDecimal shejje) {
        this.shejje = shejje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_zhongdjcfxpgtj.shixms
     *
     * @return the value of y_zhongdjcfxpgtj.shixms
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getShixms() {
        return shixms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_zhongdjcfxpgtj.shixms
     *
     * @param shixms the value for y_zhongdjcfxpgtj.shixms
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setShixms(String shixms) {
        this.shixms = shixms == null ? null : shixms.trim();
    }
}