package com.casic.oarp.datavisual.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZhongdjcfxpgtjExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public ZhongdjcfxpgtjExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZIdIsNull() {
            addCriterion("z_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZIdIsNotNull() {
            addCriterion("z_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZIdEqualTo(String value) {
            addCriterion("z_id_ =", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotEqualTo(String value) {
            addCriterion("z_id_ <>", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThan(String value) {
            addCriterion("z_id_ >", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_id_ >=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThan(String value) {
            addCriterion("z_id_ <", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThanOrEqualTo(String value) {
            addCriterion("z_id_ <=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLike(String value) {
            addCriterion("z_id_ like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotLike(String value) {
            addCriterion("z_id_ not like", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdIn(List<String> values) {
            addCriterion("z_id_ in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotIn(List<String> values) {
            addCriterion("z_id_ not in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdBetween(String value1, String value2) {
            addCriterion("z_id_ between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotBetween(String value1, String value2) {
            addCriterion("z_id_ not between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andErjdwmcIsNull() {
            addCriterion("erjdwmc is null");
            return (Criteria) this;
        }

        public Criteria andErjdwmcIsNotNull() {
            addCriterion("erjdwmc is not null");
            return (Criteria) this;
        }

        public Criteria andErjdwmcEqualTo(String value) {
            addCriterion("erjdwmc =", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcNotEqualTo(String value) {
            addCriterion("erjdwmc <>", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcGreaterThan(String value) {
            addCriterion("erjdwmc >", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcGreaterThanOrEqualTo(String value) {
            addCriterion("erjdwmc >=", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcLessThan(String value) {
            addCriterion("erjdwmc <", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcLessThanOrEqualTo(String value) {
            addCriterion("erjdwmc <=", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcLike(String value) {
            addCriterion("erjdwmc like", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcNotLike(String value) {
            addCriterion("erjdwmc not like", value, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcIn(List<String> values) {
            addCriterion("erjdwmc in", values, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcNotIn(List<String> values) {
            addCriterion("erjdwmc not in", values, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcBetween(String value1, String value2) {
            addCriterion("erjdwmc between", value1, value2, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andErjdwmcNotBetween(String value1, String value2) {
            addCriterion("erjdwmc not between", value1, value2, "erjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcIsNull() {
            addCriterion("sanjhsjdwmc is null");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcIsNotNull() {
            addCriterion("sanjhsjdwmc is not null");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcEqualTo(String value) {
            addCriterion("sanjhsjdwmc =", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcNotEqualTo(String value) {
            addCriterion("sanjhsjdwmc <>", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcGreaterThan(String value) {
            addCriterion("sanjhsjdwmc >", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcGreaterThanOrEqualTo(String value) {
            addCriterion("sanjhsjdwmc >=", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcLessThan(String value) {
            addCriterion("sanjhsjdwmc <", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcLessThanOrEqualTo(String value) {
            addCriterion("sanjhsjdwmc <=", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcLike(String value) {
            addCriterion("sanjhsjdwmc like", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcNotLike(String value) {
            addCriterion("sanjhsjdwmc not like", value, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcIn(List<String> values) {
            addCriterion("sanjhsjdwmc in", values, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcNotIn(List<String> values) {
            addCriterion("sanjhsjdwmc not in", values, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcBetween(String value1, String value2) {
            addCriterion("sanjhsjdwmc between", value1, value2, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andSanjhsjdwmcNotBetween(String value1, String value2) {
            addCriterion("sanjhsjdwmc not between", value1, value2, "sanjhsjdwmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcIsNull() {
            addCriterion("shenysxmc is null");
            return (Criteria) this;
        }

        public Criteria andShenysxmcIsNotNull() {
            addCriterion("shenysxmc is not null");
            return (Criteria) this;
        }

        public Criteria andShenysxmcEqualTo(String value) {
            addCriterion("shenysxmc =", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcNotEqualTo(String value) {
            addCriterion("shenysxmc <>", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcGreaterThan(String value) {
            addCriterion("shenysxmc >", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcGreaterThanOrEqualTo(String value) {
            addCriterion("shenysxmc >=", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcLessThan(String value) {
            addCriterion("shenysxmc <", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcLessThanOrEqualTo(String value) {
            addCriterion("shenysxmc <=", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcLike(String value) {
            addCriterion("shenysxmc like", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcNotLike(String value) {
            addCriterion("shenysxmc not like", value, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcIn(List<String> values) {
            addCriterion("shenysxmc in", values, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcNotIn(List<String> values) {
            addCriterion("shenysxmc not in", values, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcBetween(String value1, String value2) {
            addCriterion("shenysxmc between", value1, value2, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShenysxmcNotBetween(String value1, String value2) {
            addCriterion("shenysxmc not between", value1, value2, "shenysxmc");
            return (Criteria) this;
        }

        public Criteria andShixlxIsNull() {
            addCriterion("shixlx is null");
            return (Criteria) this;
        }

        public Criteria andShixlxIsNotNull() {
            addCriterion("shixlx is not null");
            return (Criteria) this;
        }

        public Criteria andShixlxEqualTo(String value) {
            addCriterion("shixlx =", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxNotEqualTo(String value) {
            addCriterion("shixlx <>", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxGreaterThan(String value) {
            addCriterion("shixlx >", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxGreaterThanOrEqualTo(String value) {
            addCriterion("shixlx >=", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxLessThan(String value) {
            addCriterion("shixlx <", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxLessThanOrEqualTo(String value) {
            addCriterion("shixlx <=", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxLike(String value) {
            addCriterion("shixlx like", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxNotLike(String value) {
            addCriterion("shixlx not like", value, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxIn(List<String> values) {
            addCriterion("shixlx in", values, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxNotIn(List<String> values) {
            addCriterion("shixlx not in", values, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxBetween(String value1, String value2) {
            addCriterion("shixlx between", value1, value2, "shixlx");
            return (Criteria) this;
        }

        public Criteria andShixlxNotBetween(String value1, String value2) {
            addCriterion("shixlx not between", value1, value2, "shixlx");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcIsNull() {
            addCriterion("zuizsydwjc is null");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcIsNotNull() {
            addCriterion("zuizsydwjc is not null");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcEqualTo(String value) {
            addCriterion("zuizsydwjc =", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcNotEqualTo(String value) {
            addCriterion("zuizsydwjc <>", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcGreaterThan(String value) {
            addCriterion("zuizsydwjc >", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcGreaterThanOrEqualTo(String value) {
            addCriterion("zuizsydwjc >=", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcLessThan(String value) {
            addCriterion("zuizsydwjc <", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcLessThanOrEqualTo(String value) {
            addCriterion("zuizsydwjc <=", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcLike(String value) {
            addCriterion("zuizsydwjc like", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcNotLike(String value) {
            addCriterion("zuizsydwjc not like", value, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcIn(List<String> values) {
            addCriterion("zuizsydwjc in", values, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcNotIn(List<String> values) {
            addCriterion("zuizsydwjc not in", values, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcBetween(String value1, String value2) {
            addCriterion("zuizsydwjc between", value1, value2, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andZuizsydwjcNotBetween(String value1, String value2) {
            addCriterion("zuizsydwjc not between", value1, value2, "zuizsydwjc");
            return (Criteria) this;
        }

        public Criteria andShenyjgIsNull() {
            addCriterion("shenyjg is null");
            return (Criteria) this;
        }

        public Criteria andShenyjgIsNotNull() {
            addCriterion("shenyjg is not null");
            return (Criteria) this;
        }

        public Criteria andShenyjgEqualTo(String value) {
            addCriterion("shenyjg =", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgNotEqualTo(String value) {
            addCriterion("shenyjg <>", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgGreaterThan(String value) {
            addCriterion("shenyjg >", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgGreaterThanOrEqualTo(String value) {
            addCriterion("shenyjg >=", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgLessThan(String value) {
            addCriterion("shenyjg <", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgLessThanOrEqualTo(String value) {
            addCriterion("shenyjg <=", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgLike(String value) {
            addCriterion("shenyjg like", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgNotLike(String value) {
            addCriterion("shenyjg not like", value, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgIn(List<String> values) {
            addCriterion("shenyjg in", values, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgNotIn(List<String> values) {
            addCriterion("shenyjg not in", values, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgBetween(String value1, String value2) {
            addCriterion("shenyjg between", value1, value2, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenyjgNotBetween(String value1, String value2) {
            addCriterion("shenyjg not between", value1, value2, "shenyjg");
            return (Criteria) this;
        }

        public Criteria andShenysjIsNull() {
            addCriterion("shenysj is null");
            return (Criteria) this;
        }

        public Criteria andShenysjIsNotNull() {
            addCriterion("shenysj is not null");
            return (Criteria) this;
        }

        public Criteria andShenysjEqualTo(Date value) {
            addCriterion("shenysj =", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjNotEqualTo(Date value) {
            addCriterion("shenysj <>", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjGreaterThan(Date value) {
            addCriterion("shenysj >", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjGreaterThanOrEqualTo(Date value) {
            addCriterion("shenysj >=", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjLessThan(Date value) {
            addCriterion("shenysj <", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjLessThanOrEqualTo(Date value) {
            addCriterion("shenysj <=", value, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjIn(List<Date> values) {
            addCriterion("shenysj in", values, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjNotIn(List<Date> values) {
            addCriterion("shenysj not in", values, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjBetween(Date value1, Date value2) {
            addCriterion("shenysj between", value1, value2, "shenysj");
            return (Criteria) this;
        }

        public Criteria andShenysjNotBetween(Date value1, Date value2) {
            addCriterion("shenysj not between", value1, value2, "shenysj");
            return (Criteria) this;
        }

        public Criteria andZhuzbmIsNull() {
            addCriterion("zhuzbm is null");
            return (Criteria) this;
        }

        public Criteria andZhuzbmIsNotNull() {
            addCriterion("zhuzbm is not null");
            return (Criteria) this;
        }

        public Criteria andZhuzbmEqualTo(String value) {
            addCriterion("zhuzbm =", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmNotEqualTo(String value) {
            addCriterion("zhuzbm <>", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmGreaterThan(String value) {
            addCriterion("zhuzbm >", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmGreaterThanOrEqualTo(String value) {
            addCriterion("zhuzbm >=", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmLessThan(String value) {
            addCriterion("zhuzbm <", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmLessThanOrEqualTo(String value) {
            addCriterion("zhuzbm <=", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmLike(String value) {
            addCriterion("zhuzbm like", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmNotLike(String value) {
            addCriterion("zhuzbm not like", value, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmIn(List<String> values) {
            addCriterion("zhuzbm in", values, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmNotIn(List<String> values) {
            addCriterion("zhuzbm not in", values, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmBetween(String value1, String value2) {
            addCriterion("zhuzbm between", value1, value2, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andZhuzbmNotBetween(String value1, String value2) {
            addCriterion("zhuzbm not between", value1, value2, "zhuzbm");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpIsNull() {
            addCriterion("fengxpgsfbghzp is null");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpIsNotNull() {
            addCriterion("fengxpgsfbghzp is not null");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpEqualTo(String value) {
            addCriterion("fengxpgsfbghzp =", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpNotEqualTo(String value) {
            addCriterion("fengxpgsfbghzp <>", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpGreaterThan(String value) {
            addCriterion("fengxpgsfbghzp >", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpGreaterThanOrEqualTo(String value) {
            addCriterion("fengxpgsfbghzp >=", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpLessThan(String value) {
            addCriterion("fengxpgsfbghzp <", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpLessThanOrEqualTo(String value) {
            addCriterion("fengxpgsfbghzp <=", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpLike(String value) {
            addCriterion("fengxpgsfbghzp like", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpNotLike(String value) {
            addCriterion("fengxpgsfbghzp not like", value, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpIn(List<String> values) {
            addCriterion("fengxpgsfbghzp in", values, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpNotIn(List<String> values) {
            addCriterion("fengxpgsfbghzp not in", values, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpBetween(String value1, String value2) {
            addCriterion("fengxpgsfbghzp between", value1, value2, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andFengxpgsfbghzpNotBetween(String value1, String value2) {
            addCriterion("fengxpgsfbghzp not between", value1, value2, "fengxpgsfbghzp");
            return (Criteria) this;
        }

        public Criteria andShixfxcdIsNull() {
            addCriterion("shixfxcd is null");
            return (Criteria) this;
        }

        public Criteria andShixfxcdIsNotNull() {
            addCriterion("shixfxcd is not null");
            return (Criteria) this;
        }

        public Criteria andShixfxcdEqualTo(String value) {
            addCriterion("shixfxcd =", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdNotEqualTo(String value) {
            addCriterion("shixfxcd <>", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdGreaterThan(String value) {
            addCriterion("shixfxcd >", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdGreaterThanOrEqualTo(String value) {
            addCriterion("shixfxcd >=", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdLessThan(String value) {
            addCriterion("shixfxcd <", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdLessThanOrEqualTo(String value) {
            addCriterion("shixfxcd <=", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdLike(String value) {
            addCriterion("shixfxcd like", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdNotLike(String value) {
            addCriterion("shixfxcd not like", value, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdIn(List<String> values) {
            addCriterion("shixfxcd in", values, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdNotIn(List<String> values) {
            addCriterion("shixfxcd not in", values, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdBetween(String value1, String value2) {
            addCriterion("shixfxcd between", value1, value2, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andShixfxcdNotBetween(String value1, String value2) {
            addCriterion("shixfxcd not between", value1, value2, "shixfxcd");
            return (Criteria) this;
        }

        public Criteria andCainqkIsNull() {
            addCriterion("cainqk is null");
            return (Criteria) this;
        }

        public Criteria andCainqkIsNotNull() {
            addCriterion("cainqk is not null");
            return (Criteria) this;
        }

        public Criteria andCainqkEqualTo(String value) {
            addCriterion("cainqk =", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkNotEqualTo(String value) {
            addCriterion("cainqk <>", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkGreaterThan(String value) {
            addCriterion("cainqk >", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkGreaterThanOrEqualTo(String value) {
            addCriterion("cainqk >=", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkLessThan(String value) {
            addCriterion("cainqk <", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkLessThanOrEqualTo(String value) {
            addCriterion("cainqk <=", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkLike(String value) {
            addCriterion("cainqk like", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkNotLike(String value) {
            addCriterion("cainqk not like", value, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkIn(List<String> values) {
            addCriterion("cainqk in", values, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkNotIn(List<String> values) {
            addCriterion("cainqk not in", values, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkBetween(String value1, String value2) {
            addCriterion("cainqk between", value1, value2, "cainqk");
            return (Criteria) this;
        }

        public Criteria andCainqkNotBetween(String value1, String value2) {
            addCriterion("cainqk not between", value1, value2, "cainqk");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNull() {
            addCriterion("z_createtime_ is null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIsNotNull() {
            addCriterion("z_createtime_ is not null");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeEqualTo(Date value) {
            addCriterion("z_createtime_ =", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotEqualTo(Date value) {
            addCriterion("z_createtime_ <>", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThan(Date value) {
            addCriterion("z_createtime_ >", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ >=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThan(Date value) {
            addCriterion("z_createtime_ <", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("z_createtime_ <=", value, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeIn(List<Date> values) {
            addCriterion("z_createtime_ in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotIn(List<Date> values) {
            addCriterion("z_createtime_ not in", values, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("z_createtime_ not between", value1, value2, "zCreatetime");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNull() {
            addCriterion("z_personnel_id_ is null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIsNotNull() {
            addCriterion("z_personnel_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdEqualTo(String value) {
            addCriterion("z_personnel_id_ =", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotEqualTo(String value) {
            addCriterion("z_personnel_id_ <>", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThan(String value) {
            addCriterion("z_personnel_id_ >", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdGreaterThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ >=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThan(String value) {
            addCriterion("z_personnel_id_ <", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLessThanOrEqualTo(String value) {
            addCriterion("z_personnel_id_ <=", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdLike(String value) {
            addCriterion("z_personnel_id_ like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotLike(String value) {
            addCriterion("z_personnel_id_ not like", value, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdIn(List<String> values) {
            addCriterion("z_personnel_id_ in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotIn(List<String> values) {
            addCriterion("z_personnel_id_ not in", values, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andZPersonnelIdNotBetween(String value1, String value2) {
            addCriterion("z_personnel_id_ not between", value1, value2, "zPersonnelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNull() {
            addCriterion("secret_level_id is null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIsNotNull() {
            addCriterion("secret_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdEqualTo(String value) {
            addCriterion("secret_level_id =", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotEqualTo(String value) {
            addCriterion("secret_level_id <>", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThan(String value) {
            addCriterion("secret_level_id >", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdGreaterThanOrEqualTo(String value) {
            addCriterion("secret_level_id >=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThan(String value) {
            addCriterion("secret_level_id <", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLessThanOrEqualTo(String value) {
            addCriterion("secret_level_id <=", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdLike(String value) {
            addCriterion("secret_level_id like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotLike(String value) {
            addCriterion("secret_level_id not like", value, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdIn(List<String> values) {
            addCriterion("secret_level_id in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotIn(List<String> values) {
            addCriterion("secret_level_id not in", values, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdBetween(String value1, String value2) {
            addCriterion("secret_level_id between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andSecretLevelIdNotBetween(String value1, String value2) {
            addCriterion("secret_level_id not between", value1, value2, "secretLevelId");
            return (Criteria) this;
        }

        public Criteria andShejjeIsNull() {
            addCriterion("shejje is null");
            return (Criteria) this;
        }

        public Criteria andShejjeIsNotNull() {
            addCriterion("shejje is not null");
            return (Criteria) this;
        }

        public Criteria andShejjeEqualTo(BigDecimal value) {
            addCriterion("shejje =", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeNotEqualTo(BigDecimal value) {
            addCriterion("shejje <>", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeGreaterThan(BigDecimal value) {
            addCriterion("shejje >", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shejje >=", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeLessThan(BigDecimal value) {
            addCriterion("shejje <", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shejje <=", value, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeIn(List<BigDecimal> values) {
            addCriterion("shejje in", values, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeNotIn(List<BigDecimal> values) {
            addCriterion("shejje not in", values, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shejje between", value1, value2, "shejje");
            return (Criteria) this;
        }

        public Criteria andShejjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shejje not between", value1, value2, "shejje");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 05 15:44:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}