package com.casic.oarp.datavisual.model.zxfk;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 审计项目表模型，
 * 用于重要度排名，审计问题金额
 */
public class AuditProjectTableModel implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.susejdw
     * 所属二级单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String susejdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjxmlx
     * 审计项目类型
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjxmlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.beisjdw
     * 被审计单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String beisjdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.danwjc
     * 单位级次
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String danwjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.shenjdw
     * 审计单位
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String shenjdw;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentlx
     * 问题类型
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String wentlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentje
     * 问题金额
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private BigDecimal wentje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.zhongycd
     * 重要程度
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String zhongycd;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.wentfssj
     * 问题发生时间
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private Date wentfssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_shenjfxwtbajzggzqkb.duczgbm
     * 督促整改部门
     * @mbg.generated Wed Jun 27 12:41:33 CST 2018
     */
    private String duczgbm;

    @Override
    public String toString() {
        return "AuditProjectTableModel{" +
                "susejdw='" + susejdw + '\'' +
                ", shenjxmlx='" + shenjxmlx + '\'' +
                ", beisjdw='" + beisjdw + '\'' +
                ", danwjc='" + danwjc + '\'' +
                ", shenjdw='" + shenjdw + '\'' +
                ", wentlx='" + wentlx + '\'' +
                ", wentje=" + wentje +
                ", zhongycd='" + zhongycd + '\'' +
                ", wentfssj=" + wentfssj +
                ", duczgbm='" + duczgbm + '\'' +
                '}';
    }

    public AuditProjectTableModel() {
    }

    public String getSusejdw() {
        return susejdw;
    }

    public void setSusejdw(String susejdw) {
        this.susejdw = susejdw;
    }

    public String getShenjxmlx() {
        return shenjxmlx;
    }

    public void setShenjxmlx(String shenjxmlx) {
        this.shenjxmlx = shenjxmlx;
    }

    public String getBeisjdw() {
        return beisjdw;
    }

    public void setBeisjdw(String beisjdw) {
        this.beisjdw = beisjdw;
    }

    public String getDanwjc() {
        return danwjc;
    }

    public void setDanwjc(String danwjc) {
        this.danwjc = danwjc;
    }

    public String getShenjdw() {
        return shenjdw;
    }

    public void setShenjdw(String shenjdw) {
        this.shenjdw = shenjdw;
    }

    public String getWentlx() {
        return wentlx;
    }

    public void setWentlx(String wentlx) {
        this.wentlx = wentlx;
    }

    public BigDecimal getWentje() {
        return wentje;
    }

    public void setWentje(BigDecimal wentje) {
        this.wentje = wentje;
    }

    public String getZhongycd() {
        return zhongycd;
    }

    public void setZhongycd(String zhongycd) {
        this.zhongycd = zhongycd;
    }

    public Date getWentfssj() {
        return wentfssj;
    }

    public void setWentfssj(Date wentfssj) {
        this.wentfssj = wentfssj;
    }

    public String getDuczgbm() {
        return duczgbm;
    }

    public void setDuczgbm(String duczgbm) {
        this.duczgbm = duczgbm;
    }
}
