package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.DsdTable;
import com.casic.oarp.datavisual.po.DsdTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsdTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    long countByExample(DsdTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int deleteByExample(DsdTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int deleteByPrimaryKey(Integer dsdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int insert(DsdTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int insertSelective(DsdTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    List<DsdTable> selectByExample(DsdTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    DsdTable selectByPrimaryKey(Integer dsdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") DsdTable record, @Param("example") DsdTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int updateByExample(@Param("record") DsdTable record, @Param("example") DsdTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int updateByPrimaryKeySelective(DsdTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsd_table
     *
     * @mbg.generated Thu Sep 20 15:25:59 CST 2018
     */
    int updateByPrimaryKey(DsdTable record);
}