package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.RiskEventsTrack;
import com.casic.oarp.datavisual.po.RiskEventsTrackExample;
import com.casic.oarp.datavisual.po.RiskEventsTrackWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RiskEventsTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    long countByExample(RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int deleteByExample(RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int deleteByPrimaryKey(String zId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int insert(RiskEventsTrackWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int insertSelective(RiskEventsTrackWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    List<RiskEventsTrackWithBLOBs> selectByExampleWithBLOBs(RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    List<RiskEventsTrack> selectByExample(RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    RiskEventsTrackWithBLOBs selectByPrimaryKey(String zId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") RiskEventsTrackWithBLOBs record, @Param("example") RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") RiskEventsTrackWithBLOBs record, @Param("example") RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByExample(@Param("record") RiskEventsTrack record, @Param("example") RiskEventsTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(RiskEventsTrackWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(RiskEventsTrackWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_risk_events_track
     *
     * @mbg.generated Wed Jul 04 10:51:13 CST 2018
     */
    int updateByPrimaryKey(RiskEventsTrack record);
}