package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.Zhongdjcfxpgtj;
import com.casic.oarp.datavisual.po.ZhongdjcfxpgtjExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ZhongdjcfxpgtjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    long countByExample(ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int deleteByExample(ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int deleteByPrimaryKey(String zId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int insert(Zhongdjcfxpgtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int insertSelective(Zhongdjcfxpgtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    List<Zhongdjcfxpgtj> selectByExampleWithBLOBs(ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    List<Zhongdjcfxpgtj> selectByExample(ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    Zhongdjcfxpgtj selectByPrimaryKey(String zId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Zhongdjcfxpgtj record, @Param("example") ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Zhongdjcfxpgtj record, @Param("example") ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByExample(@Param("record") Zhongdjcfxpgtj record, @Param("example") ZhongdjcfxpgtjExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByPrimaryKeySelective(Zhongdjcfxpgtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Zhongdjcfxpgtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_zhongdjcfxpgtj
     *
     * @mbg.generated Thu Jul 05 15:44:33 CST 2018
     */
    int updateByPrimaryKey(Zhongdjcfxpgtj record);
}